# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'real_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HSMainWindow(object):
    def setupUi(self, HSMainWindow):
        HSMainWindow.setObjectName("HSMainWindow")
        HSMainWindow.resize(956, 645)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HSMainWindow.sizePolicy().hasHeightForWidth())
        HSMainWindow.setSizePolicy(sizePolicy)
        HSMainWindow.setMouseTracking(True)
        HSMainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        HSMainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        HSMainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(HSMainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1310, 75))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newprod_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newprod_button.sizePolicy().hasHeightForWidth())
        self.newprod_button.setSizePolicy(sizePolicy)
        self.newprod_button.setObjectName("newprod_button")
        self.buttonGroup = QtWidgets.QButtonGroup(HSMainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.newprod_button)
        self.horizontalLayout.addWidget(self.newprod_button)
        self.edit_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_button.sizePolicy().hasHeightForWidth())
        self.edit_button.setSizePolicy(sizePolicy)
        self.edit_button.setObjectName("edit_button")
        self.buttonGroup.addButton(self.edit_button)
        self.horizontalLayout.addWidget(self.edit_button)
        self.preview_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_button.sizePolicy().hasHeightForWidth())
        self.preview_button.setSizePolicy(sizePolicy)
        self.preview_button.setObjectName("preview_button")
        self.buttonGroup.addButton(self.preview_button)
        self.horizontalLayout.addWidget(self.preview_button)
        self.print_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_button.sizePolicy().hasHeightForWidth())
        self.print_button.setSizePolicy(sizePolicy)
        self.print_button.setObjectName("print_button")
        self.buttonGroup.addButton(self.print_button)
        self.horizontalLayout.addWidget(self.print_button)
        self.delete_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_button.sizePolicy().hasHeightForWidth())
        self.delete_button.setSizePolicy(sizePolicy)
        self.delete_button.setObjectName("delete_button")
        self.buttonGroup.addButton(self.delete_button)
        self.horizontalLayout.addWidget(self.delete_button)
        self.synch_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synch_button.sizePolicy().hasHeightForWidth())
        self.synch_button.setSizePolicy(sizePolicy)
        self.synch_button.setIconSize(QtCore.QSize(40, 40))
        self.synch_button.setFlat(False)
        self.synch_button.setObjectName("synch_button")
        self.buttonGroup.addButton(self.synch_button)
        self.horizontalLayout.addWidget(self.synch_button)
        spacerItem = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.search_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.search_lbl.setObjectName("search_lbl")
        self.horizontalLayout_4.addWidget(self.search_lbl)
        self.search_box = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.search_box.setObjectName("search_box")
        self.horizontalLayout_4.addWidget(self.search_box)
        self.search_btn = QtWidgets.QCommandLinkButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn.sizePolicy().hasHeightForWidth())
        self.search_btn.setSizePolicy(sizePolicy)
        self.search_btn.setText("")
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_4.addWidget(self.search_btn)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(195, 80, 721, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.catalog_table = QtWidgets.QTableView(self.frame)
        self.catalog_table.setGeometry(QtCore.QRect(0, 0, 721, 521))
        self.catalog_table.setMouseTracking(True)
        self.catalog_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.catalog_table.setFrameShape(QtWidgets.QFrame.Box)
        self.catalog_table.setSortingEnabled(True)
        self.catalog_table.setObjectName("catalog_table")
        self.catalog_table.verticalHeader().setVisible(False)
        self.orders_list = QtWidgets.QTableView(self.frame)
        self.orders_list.setEnabled(True)
        self.orders_list.setGeometry(QtCore.QRect(0, 0, 721, 521))
        self.orders_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.orders_list.setFrameShape(QtWidgets.QFrame.Box)
        self.orders_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.orders_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.orders_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.orders_list.setObjectName("orders_list")
        self.orders_list.horizontalHeader().setVisible(False)
        self.orders_list.verticalHeader().setVisible(False)
        self.pending_upload_table = QtWidgets.QTableView(self.frame)
        self.pending_upload_table.setGeometry(QtCore.QRect(0, 0, 721, 521))
        self.pending_upload_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.pending_upload_table.setObjectName("pending_upload_table")
        self.pending_upload_table.verticalHeader().setVisible(False)
        self.orders_list.raise_()
        self.pending_upload_table.raise_()
        self.catalog_table.raise_()
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 181, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.active_cat_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_cat_button.sizePolicy().hasHeightForWidth())
        self.active_cat_button.setSizePolicy(sizePolicy)
        self.active_cat_button.setMaximumSize(QtCore.QSize(16777215, 23))
        self.active_cat_button.setCheckable(False)
        self.active_cat_button.setObjectName("active_cat_button")
        self.main_view_group = QtWidgets.QButtonGroup(HSMainWindow)
        self.main_view_group.setObjectName("main_view_group")
        self.main_view_group.addButton(self.active_cat_button)
        self.verticalLayout.addWidget(self.active_cat_button)
        self.inactive_cat_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.inactive_cat_button.setObjectName("inactive_cat_button")
        self.main_view_group.addButton(self.inactive_cat_button)
        self.verticalLayout.addWidget(self.inactive_cat_button)
        self.pending_upload_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pending_upload_button.setObjectName("pending_upload_button")
        self.main_view_group.addButton(self.pending_upload_button)
        self.verticalLayout.addWidget(self.pending_upload_button)
        self.order_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.order_btn.setObjectName("order_btn")
        self.main_view_group.addButton(self.order_btn)
        self.verticalLayout.addWidget(self.order_btn)
        self.horizontalLayoutWidget.raise_()
        self.frame.raise_()
        self.verticalLayoutWidget.raise_()
        self.layoutWidget.raise_()
        HSMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HSMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuSynchronize = QtWidgets.QMenu(self.menuFile)
        self.menuSynchronize.setObjectName("menuSynchronize")
        self.menuLoad = QtWidgets.QMenu(self.menuFile)
        self.menuLoad.setObjectName("menuLoad")
        self.menuExport_CSV = QtWidgets.QMenu(self.menuFile)
        self.menuExport_CSV.setObjectName("menuExport_CSV")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        HSMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HSMainWindow)
        self.statusbar.setObjectName("statusbar")
        HSMainWindow.setStatusBar(self.statusbar)
        self.actionNewItem = QtWidgets.QAction(HSMainWindow)
        self.actionNewItem.setObjectName("actionNewItem")
        self.actionTemplate = QtWidgets.QAction(HSMainWindow)
        self.actionTemplate.setObjectName("actionTemplate")
        self.actionClose = QtWidgets.QAction(HSMainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAll_Items = QtWidgets.QAction(HSMainWindow)
        self.actionAll_Items.setObjectName("actionAll_Items")
        self.actionCheck_for_New_Items = QtWidgets.QAction(HSMainWindow)
        self.actionCheck_for_New_Items.setObjectName("actionCheck_for_New_Items")
        self.actionUpload_Waiting_Items = QtWidgets.QAction(HSMainWindow)
        self.actionUpload_Waiting_Items.setObjectName("actionUpload_Waiting_Items")
        self.actionN_A = QtWidgets.QAction(HSMainWindow)
        self.actionN_A.setObjectName("actionN_A")
        self.actionInventory_CSV = QtWidgets.QAction(HSMainWindow)
        self.actionInventory_CSV.setObjectName("actionInventory_CSV")
        self.actionActive_Catalog = QtWidgets.QAction(HSMainWindow)
        self.actionActive_Catalog.setObjectName("actionActive_Catalog")
        self.actionInactive_Items = QtWidgets.QAction(HSMainWindow)
        self.actionInactive_Items.setObjectName("actionInactive_Items")
        self.actionGlobal_Catalog = QtWidgets.QAction(HSMainWindow)
        self.actionGlobal_Catalog.setObjectName("actionGlobal_Catalog")
        self.menuNew.addAction(self.actionNewItem)
        self.menuNew.addAction(self.actionTemplate)
        self.menuSynchronize.addAction(self.actionAll_Items)
        self.menuSynchronize.addAction(self.actionCheck_for_New_Items)
        self.menuSynchronize.addAction(self.actionUpload_Waiting_Items)
        self.menuLoad.addAction(self.actionInventory_CSV)
        self.menuExport_CSV.addAction(self.actionActive_Catalog)
        self.menuExport_CSV.addAction(self.actionInactive_Items)
        self.menuExport_CSV.addAction(self.actionGlobal_Catalog)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addAction(self.menuExport_CSV.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSynchronize.menuAction())
        self.menuHelp.addAction(self.actionN_A)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HSMainWindow)
        QtCore.QMetaObject.connectSlotsByName(HSMainWindow)

    def retranslateUi(self, HSMainWindow):
        _translate = QtCore.QCoreApplication.translate
        HSMainWindow.setWindowTitle(_translate("HSMainWindow", "HangarSwap Seller App"))
        self.newprod_button.setText(_translate("HSMainWindow", "New"))
        self.edit_button.setText(_translate("HSMainWindow", "Edit"))
        self.preview_button.setText(_translate("HSMainWindow", "Preview"))
        self.print_button.setText(_translate("HSMainWindow", "Print"))
        self.delete_button.setText(_translate("HSMainWindow", "Delete"))
        self.synch_button.setText(_translate("HSMainWindow", "Synchronize"))
        self.search_lbl.setText(_translate("HSMainWindow", "Search"))
        self.active_cat_button.setText(_translate("HSMainWindow", "Active Catalog"))
        self.inactive_cat_button.setText(_translate("HSMainWindow", "Inactive Items"))
        self.pending_upload_button.setText(_translate("HSMainWindow", "Waiting to Upload"))
        self.order_btn.setText(_translate("HSMainWindow", "Orders"))
        self.menuFile.setTitle(_translate("HSMainWindow", "File"))
        self.menuNew.setTitle(_translate("HSMainWindow", "New"))
        self.menuSynchronize.setTitle(_translate("HSMainWindow", "Synchronize"))
        self.menuLoad.setTitle(_translate("HSMainWindow", "Load"))
        self.menuExport_CSV.setTitle(_translate("HSMainWindow", "Export CSV"))
        self.menuHelp.setTitle(_translate("HSMainWindow", "Help"))
        self.actionNewItem.setText(_translate("HSMainWindow", "Item"))
        self.actionTemplate.setText(_translate("HSMainWindow", "Template"))
        self.actionClose.setText(_translate("HSMainWindow", "Close"))
        self.actionAll_Items.setText(_translate("HSMainWindow", "All Items"))
        self.actionCheck_for_New_Items.setText(_translate("HSMainWindow", "Check for New Items"))
        self.actionUpload_Waiting_Items.setText(_translate("HSMainWindow", "Upload Waiting Items"))
        self.actionN_A.setText(_translate("HSMainWindow", "N/A"))
        self.actionInventory_CSV.setText(_translate("HSMainWindow", "Inventory CSV"))
        self.actionActive_Catalog.setText(_translate("HSMainWindow", "Active"))
        self.actionInactive_Items.setText(_translate("HSMainWindow", "Inactive"))
        self.actionGlobal_Catalog.setText(_translate("HSMainWindow", "Global Catalog"))

