# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editProductDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editProduct(object):
    def setupUi(self, editProduct):
        editProduct.setObjectName("editProduct")
        editProduct.setWindowModality(QtCore.Qt.WindowModal)
        editProduct.resize(617, 642)
        self.verticalLayoutWidget = QtWidgets.QWidget(editProduct)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 1, 381, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newproduct_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newproduct_lbl_2.sizePolicy().hasHeightForWidth())
        self.newproduct_lbl_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.newproduct_lbl_2.setFont(font)
        self.newproduct_lbl_2.setObjectName("newproduct_lbl_2")
        self.verticalLayout_2.addWidget(self.newproduct_lbl_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.name_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name_lbl_2.setObjectName("name_lbl_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_lbl_2)
        self.name_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name_le_2.setObjectName("name_le_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_le_2)
        self.desc_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.desc_lbl_2.setObjectName("desc_lbl_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.desc_lbl_2)
        self.desc_te_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.desc_te_2.setObjectName("desc_te_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.desc_te_2)
        self.cat_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cat_lbl_2.setObjectName("cat_lbl_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cat_lbl_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cat_options_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat_options_2.sizePolicy().hasHeightForWidth())
        self.cat_options_2.setSizePolicy(sizePolicy)
        self.cat_options_2.setObjectName("cat_options_2")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.cat_options_2.addItem("")
        self.horizontalLayout_12.addWidget(self.cat_options_2)
        self.subcat_options_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.subcat_options_2.setObjectName("subcat_options_2")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.subcat_options_2.addItem("")
        self.horizontalLayout_12.addWidget(self.subcat_options_2)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.cond_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cond_lbl_2.setObjectName("cond_lbl_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cond_lbl_2)
        self.cond_options_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cond_options_2.sizePolicy().hasHeightForWidth())
        self.cond_options_2.setSizePolicy(sizePolicy)
        self.cond_options_2.setMinimumSize(QtCore.QSize(50, 20))
        self.cond_options_2.setBaseSize(QtCore.QSize(50, 0))
        self.cond_options_2.setObjectName("cond_options_2")
        self.cond_options_2.addItem("")
        self.cond_options_2.addItem("")
        self.cond_options_2.addItem("")
        self.cond_options_2.addItem("")
        self.cond_options_2.addItem("")
        self.cond_options_2.addItem("")
        self.cond_options_2.addItem("")
        self.cond_options_2.addItem("")
        self.cond_options_2.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cond_options_2)
        self.qty_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.qty_lbl_2.setObjectName("qty_lbl_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.qty_lbl_2)
        self.qty_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.qty_le_2.setObjectName("qty_le_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.qty_le_2)
        self.mpn_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mpn_lbl_2.setObjectName("mpn_lbl_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mpn_lbl_2)
        self.pn_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pn_le_2.setObjectName("pn_le_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pn_le_2)
        self.ampn_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ampn_lbl_2.setObjectName("ampn_lbl_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.ampn_lbl_2)
        self.apn_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.apn_le_2.setObjectName("apn_le_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.apn_le_2)
        self.sn_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sn_lbl_2.setObjectName("sn_lbl_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.sn_lbl_2)
        self.sn_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sn_le_2.setObjectName("sn_le_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.sn_le_2)
        self.sku_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sku_lbl_2.setObjectName("sku_lbl_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.sku_lbl_2)
        self.sku_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sku_le_2.setObjectName("sku_le_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.sku_le_2)
        self.mfr_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mfr_lbl_2.setObjectName("mfr_lbl_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.mfr_lbl_2)
        self.mfr_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.mfr_le_2.setObjectName("mfr_le_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.mfr_le_2)
        self.price_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.price_lbl_2.setObjectName("price_lbl_2")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.price_lbl_2)
        self.price_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.price_le_2.setObjectName("price_le_2")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.price_le_2)
        self.ship_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ship_lbl_2.setObjectName("ship_lbl_2")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.ship_lbl_2)
        self.ship_le_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ship_le_2.setObjectName("ship_le_2")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.ship_le_2)
        self.core_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.core_lbl_2.setObjectName("core_lbl_2")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.core_lbl_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.core_yes_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.core_yes_2.sizePolicy().hasHeightForWidth())
        self.core_yes_2.setSizePolicy(sizePolicy)
        self.core_yes_2.setObjectName("core_yes_2")
        self.horizontalLayout_2.addWidget(self.core_yes_2)
        self.core_no_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.core_no_2.sizePolicy().hasHeightForWidth())
        self.core_no_2.setSizePolicy(sizePolicy)
        self.core_no_2.setObjectName("core_no_2")
        self.horizontalLayout_2.addWidget(self.core_no_2)
        self.formLayout_2.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.img_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.img_lbl_2.setObjectName("img_lbl_2")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.img_lbl_2)
        self.img_upload_btn_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_upload_btn_2.sizePolicy().hasHeightForWidth())
        self.img_upload_btn_2.setSizePolicy(sizePolicy)
        self.img_upload_btn_2.setObjectName("img_upload_btn_2")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.img_upload_btn_2)
        self.active_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.active_lbl_2.setObjectName("active_lbl_2")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.active_lbl_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.active_yes_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_yes_2.sizePolicy().hasHeightForWidth())
        self.active_yes_2.setSizePolicy(sizePolicy)
        self.active_yes_2.setObjectName("active_yes_2")
        self.horizontalLayout_13.addWidget(self.active_yes_2)
        self.active_no_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.active_no_2.setObjectName("active_no_2")
        self.horizontalLayout_13.addWidget(self.active_no_2)
        self.formLayout_2.setLayout(14, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.onsale_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.onsale_lbl_2.setObjectName("onsale_lbl_2")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.onsale_lbl_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.sale_yes_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sale_yes_2.sizePolicy().hasHeightForWidth())
        self.sale_yes_2.setSizePolicy(sizePolicy)
        self.sale_yes_2.setObjectName("sale_yes_2")
        self.horizontalLayout_14.addWidget(self.sale_yes_2)
        self.sale_no_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sale_no_2.setObjectName("sale_no_2")
        self.horizontalLayout_14.addWidget(self.sale_no_2)
        self.formLayout_2.setLayout(15, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.offer_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.offer_lbl_2.setObjectName("offer_lbl_2")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.offer_lbl_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.offer_yes_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offer_yes_2.sizePolicy().hasHeightForWidth())
        self.offer_yes_2.setSizePolicy(sizePolicy)
        self.offer_yes_2.setObjectName("offer_yes_2")
        self.horizontalLayout_15.addWidget(self.offer_yes_2)
        self.offer_no_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.offer_no_2.setObjectName("offer_no_2")
        self.horizontalLayout_15.addWidget(self.offer_no_2)
        self.formLayout_2.setLayout(16, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.feat_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.feat_lbl_2.setObjectName("feat_lbl_2")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.feat_lbl_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.feat_yes_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feat_yes_2.sizePolicy().hasHeightForWidth())
        self.feat_yes_2.setSizePolicy(sizePolicy)
        self.feat_yes_2.setObjectName("feat_yes_2")
        self.horizontalLayout_16.addWidget(self.feat_yes_2)
        self.feat_no_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.feat_no_2.setObjectName("feat_no_2")
        self.horizontalLayout_16.addWidget(self.feat_no_2)
        self.formLayout_2.setLayout(17, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(editProduct)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 601, 381, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.upload_new_button_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.upload_new_button_2.setObjectName("upload_new_button_2")
        self.horizontalLayout_17.addWidget(self.upload_new_button_2)
        self.cancel_new_button_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.cancel_new_button_2.setObjectName("cancel_new_button_2")
        self.horizontalLayout_17.addWidget(self.cancel_new_button_2)
        self.img_groupbox = QtWidgets.QGroupBox(editProduct)
        self.img_groupbox.setGeometry(QtCore.QRect(389, 0, 221, 601))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.img_groupbox.setFont(font)
        self.img_groupbox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.img_groupbox.setObjectName("img_groupbox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.img_groupbox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 201, 571))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.img1_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img1_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img1_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img1_lbl_2.setText("")
        self.img1_lbl_2.setObjectName("img1_lbl_2")
        self.gridLayout_2.addWidget(self.img1_lbl_2, 0, 0, 1, 1)
        self.img2_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img2_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img2_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img2_lbl_2.setText("")
        self.img2_lbl_2.setObjectName("img2_lbl_2")
        self.gridLayout_2.addWidget(self.img2_lbl_2, 0, 1, 1, 1)
        self.img7_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img7_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img7_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img7_lbl_2.setText("")
        self.img7_lbl_2.setObjectName("img7_lbl_2")
        self.gridLayout_2.addWidget(self.img7_lbl_2, 3, 0, 1, 1)
        self.img4_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img4_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img4_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img4_lbl_2.setText("")
        self.img4_lbl_2.setObjectName("img4_lbl_2")
        self.gridLayout_2.addWidget(self.img4_lbl_2, 1, 1, 1, 1)
        self.img8_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img8_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img8_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img8_lbl_2.setText("")
        self.img8_lbl_2.setObjectName("img8_lbl_2")
        self.gridLayout_2.addWidget(self.img8_lbl_2, 3, 1, 1, 1)
        self.img5_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img5_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img5_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img5_lbl_2.setText("")
        self.img5_lbl_2.setObjectName("img5_lbl_2")
        self.gridLayout_2.addWidget(self.img5_lbl_2, 2, 0, 1, 1)
        self.img6_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img6_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img6_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img6_lbl_2.setText("")
        self.img6_lbl_2.setObjectName("img6_lbl_2")
        self.gridLayout_2.addWidget(self.img6_lbl_2, 2, 1, 1, 1)
        self.img3_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img3_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img3_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img3_lbl_2.setText("")
        self.img3_lbl_2.setObjectName("img3_lbl_2")
        self.gridLayout_2.addWidget(self.img3_lbl_2, 1, 0, 1, 1)
        self.img9_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img9_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img9_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img9_lbl_2.setText("")
        self.img9_lbl_2.setObjectName("img9_lbl_2")
        self.gridLayout_2.addWidget(self.img9_lbl_2, 4, 0, 1, 1)
        self.img10_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img10_lbl_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.img10_lbl_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img10_lbl_2.setText("")
        self.img10_lbl_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.img10_lbl_2.setObjectName("img10_lbl_2")
        self.gridLayout_2.addWidget(self.img10_lbl_2, 4, 1, 1, 1)

        self.retranslateUi(editProduct)
        self.cat_options_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(editProduct)

    def retranslateUi(self, editProduct):
        _translate = QtCore.QCoreApplication.translate
        editProduct.setWindowTitle(_translate("editProduct", "Edit a Product"))
        self.newproduct_lbl_2.setText(_translate("editProduct", "Edit Product"))
        self.name_lbl_2.setText(_translate("editProduct", "Product Name*"))
        self.desc_lbl_2.setText(_translate("editProduct", "Product Description*"))
        self.cat_lbl_2.setText(_translate("editProduct", "Product Category*"))
        self.cat_options_2.setItemText(0, _translate("editProduct", "Airboat"))
        self.cat_options_2.setItemText(1, _translate("editProduct", "Aircraft For Sale"))
        self.cat_options_2.setItemText(2, _translate("editProduct", "Airframe"))
        self.cat_options_2.setItemText(3, _translate("editProduct", "Art"))
        self.cat_options_2.setItemText(4, _translate("editProduct", "Avionics"))
        self.cat_options_2.setItemText(5, _translate("editProduct", "Electrical"))
        self.cat_options_2.setItemText(6, _translate("editProduct", "Experimental"))
        self.cat_options_2.setItemText(7, _translate("editProduct", "Hardware & Tools"))
        self.cat_options_2.setItemText(8, _translate("editProduct", "Landing Gear"))
        self.cat_options_2.setItemText(9, _translate("editProduct", "Misc"))
        self.cat_options_2.setItemText(10, _translate("editProduct", "Pilot Supplies"))
        self.cat_options_2.setItemText(11, _translate("editProduct", "Powerplant"))
        self.cat_options_2.setItemText(12, _translate("editProduct", "Wheels & Brakes"))
        self.subcat_options_2.setItemText(0, _translate("editProduct", "---"))
        self.subcat_options_2.setItemText(1, _translate("editProduct", "Aerobatic"))
        self.subcat_options_2.setItemText(2, _translate("editProduct", "Aeronca"))
        self.subcat_options_2.setItemText(3, _translate("editProduct", "Amphibian"))
        self.subcat_options_2.setItemText(4, _translate("editProduct", "Antique"))
        self.subcat_options_2.setItemText(5, _translate("editProduct", "Beechcraft"))
        self.subcat_options_2.setItemText(6, _translate("editProduct", "Bellanca"))
        self.subcat_options_2.setItemText(7, _translate("editProduct", "Cessna"))
        self.subcat_options_2.setItemText(8, _translate("editProduct", "Cirrus"))
        self.subcat_options_2.setItemText(9, _translate("editProduct", "Control Surfaces"))
        self.subcat_options_2.setItemText(10, _translate("editProduct", "General Parts"))
        self.subcat_options_2.setItemText(11, _translate("editProduct", "Helicopter"))
        self.subcat_options_2.setItemText(12, _translate("editProduct", "Interior"))
        self.subcat_options_2.setItemText(13, _translate("editProduct", "Luscombe"))
        self.subcat_options_2.setItemText(14, _translate("editProduct", "Mooney"))
        self.subcat_options_2.setItemText(15, _translate("editProduct", "Other"))
        self.subcat_options_2.setItemText(16, _translate("editProduct", "Piper"))
        self.subcat_options_2.setItemText(17, _translate("editProduct", "Taylorcraft"))
        self.subcat_options_2.setItemText(18, _translate("editProduct", "Warbird"))
        self.subcat_options_2.setItemText(19, _translate("editProduct", "Antennas"))
        self.subcat_options_2.setItemText(20, _translate("editProduct", "Audio Panels"))
        self.subcat_options_2.setItemText(21, _translate("editProduct", "AutoPilot"))
        self.subcat_options_2.setItemText(22, _translate("editProduct", "ELTs"))
        self.subcat_options_2.setItemText(23, _translate("editProduct", "Engine Monitors"))
        self.subcat_options_2.setItemText(24, _translate("editProduct", "GPS"))
        self.subcat_options_2.setItemText(25, _translate("editProduct", "Indicators"))
        self.subcat_options_2.setItemText(26, _translate("editProduct", "Intercoms"))
        self.subcat_options_2.setItemText(27, _translate("editProduct", "Nav/Coms"))
        self.subcat_options_2.setItemText(28, _translate("editProduct", "Other"))
        self.subcat_options_2.setItemText(29, _translate("editProduct", "Packages"))
        self.subcat_options_2.setItemText(30, _translate("editProduct", "Pitot Tubes"))
        self.subcat_options_2.setItemText(31, _translate("editProduct", "Transponders"))
        self.subcat_options_2.setItemText(32, _translate("editProduct", "Trays & Connectors"))
        self.subcat_options_2.setItemText(33, _translate("editProduct", "Weather Systems"))
        self.subcat_options_2.setItemText(34, _translate("editProduct", "Batteries"))
        self.subcat_options_2.setItemText(35, _translate("editProduct", "Lighting"))
        self.subcat_options_2.setItemText(36, _translate("editProduct", "Other"))
        self.subcat_options_2.setItemText(37, _translate("editProduct", "Jacks"))
        self.subcat_options_2.setItemText(38, _translate("editProduct", "Nuts & Bolts"))
        self.subcat_options_2.setItemText(39, _translate("editProduct", "Other"))
        self.subcat_options_2.setItemText(40, _translate("editProduct", "Rivets"))
        self.subcat_options_2.setItemText(41, _translate("editProduct", "Testing Equipment"))
        self.subcat_options_2.setItemText(42, _translate("editProduct", "Tools"))
        self.subcat_options_2.setItemText(43, _translate("editProduct", "Amphibian"))
        self.subcat_options_2.setItemText(44, _translate("editProduct", "Skis"))
        self.subcat_options_2.setItemText(45, _translate("editProduct", "Tailwheel"))
        self.subcat_options_2.setItemText(46, _translate("editProduct", "Tires & Tubes"))
        self.subcat_options_2.setItemText(47, _translate("editProduct", "Wheels & Brakes"))
        self.subcat_options_2.setItemText(48, _translate("editProduct", "Aviator Accessories"))
        self.subcat_options_2.setItemText(49, _translate("editProduct", "Bags"))
        self.subcat_options_2.setItemText(50, _translate("editProduct", "Books"))
        self.subcat_options_2.setItemText(51, _translate("editProduct", "Collectibles"))
        self.subcat_options_2.setItemText(52, _translate("editProduct", "Covers & Accessories"))
        self.subcat_options_2.setItemText(53, _translate("editProduct", "Headsets"))
        self.subcat_options_2.setItemText(54, _translate("editProduct", "Manuals"))
        self.subcat_options_2.setItemText(55, _translate("editProduct", "Oils, Liquids & Sprays"))
        self.subcat_options_2.setItemText(56, _translate("editProduct", "Other"))
        self.subcat_options_2.setItemText(57, _translate("editProduct", "Pilot Wear"))
        self.subcat_options_2.setItemText(58, _translate("editProduct", "Safety"))
        self.subcat_options_2.setItemText(59, _translate("editProduct", "Stickers & Decals"))
        self.subcat_options_2.setItemText(60, _translate("editProduct", "Tow"))
        self.subcat_options_2.setItemText(61, _translate("editProduct", "Engine Parts"))
        self.subcat_options_2.setItemText(62, _translate("editProduct", "Engines"))
        self.subcat_options_2.setItemText(63, _translate("editProduct", "Environmental"))
        self.subcat_options_2.setItemText(64, _translate("editProduct", "Exhaust"))
        self.subcat_options_2.setItemText(65, _translate("editProduct", "Fuel System"))
        self.subcat_options_2.setItemText(66, _translate("editProduct", "General Parts"))
        self.subcat_options_2.setItemText(67, _translate("editProduct", "Propellers"))
        self.cond_lbl_2.setText(_translate("editProduct", "Product Condition*"))
        self.cond_options_2.setItemText(0, _translate("editProduct", "As Removed"))
        self.cond_options_2.setItemText(1, _translate("editProduct", "Serviceable"))
        self.cond_options_2.setItemText(2, _translate("editProduct", "Overhauled"))
        self.cond_options_2.setItemText(3, _translate("editProduct", "New Stock"))
        self.cond_options_2.setItemText(4, _translate("editProduct", "Repairable"))
        self.cond_options_2.setItemText(5, _translate("editProduct", "New Surplus (NOS)"))
        self.cond_options_2.setItemText(6, _translate("editProduct", "Beyond Repair"))
        self.cond_options_2.setItemText(7, _translate("editProduct", "Unknown"))
        self.cond_options_2.setItemText(8, _translate("editProduct", "Core"))
        self.qty_lbl_2.setText(_translate("editProduct", "Qty Available*"))
        self.mpn_lbl_2.setText(_translate("editProduct", "Part Number"))
        self.ampn_lbl_2.setText(_translate("editProduct", "Alt Part Number"))
        self.sn_lbl_2.setText(_translate("editProduct", "Serial Number"))
        self.sku_lbl_2.setText(_translate("editProduct", "SKU"))
        self.mfr_lbl_2.setText(_translate("editProduct", "Manufacturer"))
        self.price_lbl_2.setText(_translate("editProduct", "Price*"))
        self.ship_lbl_2.setText(_translate("editProduct", "Shipping Cost*"))
        self.core_lbl_2.setText(_translate("editProduct", "Has Core Charge?"))
        self.core_yes_2.setText(_translate("editProduct", "Yes"))
        self.core_no_2.setText(_translate("editProduct", "No"))
        self.img_lbl_2.setText(_translate("editProduct", "Default Image:"))
        self.img_upload_btn_2.setText(_translate("editProduct", "Choose Image"))
        self.active_lbl_2.setText(_translate("editProduct", "Active"))
        self.active_yes_2.setText(_translate("editProduct", "Yes"))
        self.active_no_2.setText(_translate("editProduct", "No"))
        self.onsale_lbl_2.setText(_translate("editProduct", "On Sale"))
        self.sale_yes_2.setText(_translate("editProduct", "Yes"))
        self.sale_no_2.setText(_translate("editProduct", "No"))
        self.offer_lbl_2.setText(_translate("editProduct", "Allow Best Offer"))
        self.offer_yes_2.setText(_translate("editProduct", "Yes"))
        self.offer_no_2.setText(_translate("editProduct", "No"))
        self.feat_lbl_2.setText(_translate("editProduct", "Featured"))
        self.feat_yes_2.setText(_translate("editProduct", "Yes"))
        self.feat_no_2.setText(_translate("editProduct", "No"))
        self.upload_new_button_2.setText(_translate("editProduct", "Submit"))
        self.cancel_new_button_2.setText(_translate("editProduct", "Cancel"))
        self.img_groupbox.setTitle(_translate("editProduct", "Product Images"))

