# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_redesign.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HSMainWindow(object):
    def setupUi(self, HSMainWindow):
        HSMainWindow.setObjectName("HSMainWindow")
        HSMainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HSMainWindow.sizePolicy().hasHeightForWidth())
        HSMainWindow.setSizePolicy(sizePolicy)
        HSMainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        HSMainWindow.setFont(font)
        HSMainWindow.setMouseTracking(True)
        HSMainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HSMainWindow.setWindowIcon(icon)
        HSMainWindow.setStyleSheet("QMenuBar {\n"
"    background-color: rgb(54, 56, 67);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        HSMainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        HSMainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(HSMainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sidebar_2 = QtWidgets.QFrame(self.centralwidget)
        self.sidebar_2.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"font: 8pt \"Open Sans\";\n"
"")
        self.sidebar_2.setObjectName("sidebar_2")
        self.sidebar = QtWidgets.QVBoxLayout(self.sidebar_2)
        self.sidebar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.sidebar.setSpacing(0)
        self.sidebar.setObjectName("sidebar")
        self.label = QtWidgets.QLabel(self.sidebar_2)
        self.label.setObjectName("label")
        self.sidebar.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.landingBtn = QtWidgets.QPushButton(self.sidebar_2)
        self.landingBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.landingBtn.setStyleSheet("QPushButton{border-color: rgb(231, 231, 231);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(62, 112, 201);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(226, 226, 226);\n"
"border-color: rgb(255,255,255);\n"
"color: rgb(255,255,255);\n"
"}")
        self.landingBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/HangarSwapLogo_sm1_new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.landingBtn.setIcon(icon1)
        self.landingBtn.setIconSize(QtCore.QSize(120, 23))
        self.landingBtn.setObjectName("landingBtn")
        self.sidebar.addWidget(self.landingBtn)
        self.catalogGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catalogGroupBox.sizePolicy().hasHeightForWidth())
        self.catalogGroupBox.setSizePolicy(sizePolicy)
        self.catalogGroupBox.setFlat(True)
        self.catalogGroupBox.setObjectName("catalogGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.catalogGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addProductBtn_2 = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addProductBtn_2.sizePolicy().hasHeightForWidth())
        self.addProductBtn_2.setSizePolicy(sizePolicy)
        self.addProductBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addProductBtn_2.setObjectName("addProductBtn_2")
        self.verticalLayout_2.addWidget(self.addProductBtn_2)
        self.productsBtn = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productsBtn.sizePolicy().hasHeightForWidth())
        self.productsBtn.setSizePolicy(sizePolicy)
        self.productsBtn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.productsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.productsBtn.setStyleSheet("")
        self.productsBtn.setCheckable(False)
        self.productsBtn.setAutoExclusive(True)
        self.productsBtn.setFlat(False)
        self.productsBtn.setObjectName("productsBtn")
        self.verticalLayout_2.addWidget(self.productsBtn)
        self.pendBtn = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pendBtn.sizePolicy().hasHeightForWidth())
        self.pendBtn.setSizePolicy(sizePolicy)
        self.pendBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pendBtn.setObjectName("pendBtn")
        self.main_view_group = QtWidgets.QButtonGroup(HSMainWindow)
        self.main_view_group.setObjectName("main_view_group")
        self.main_view_group.addButton(self.pendBtn)
        self.verticalLayout_2.addWidget(self.pendBtn)
        self.sidebar.addWidget(self.catalogGroupBox)
        self.salesGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salesGroupBox.sizePolicy().hasHeightForWidth())
        self.salesGroupBox.setSizePolicy(sizePolicy)
        self.salesGroupBox.setFlat(True)
        self.salesGroupBox.setObjectName("salesGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.salesGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ordersBtn = QtWidgets.QPushButton(self.salesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ordersBtn.sizePolicy().hasHeightForWidth())
        self.ordersBtn.setSizePolicy(sizePolicy)
        self.ordersBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ordersBtn.setObjectName("ordersBtn")
        self.verticalLayout_3.addWidget(self.ordersBtn)
        self.sidebar.addWidget(self.salesGroupBox)
        self.accountGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountGroupBox.sizePolicy().hasHeightForWidth())
        self.accountGroupBox.setSizePolicy(sizePolicy)
        self.accountGroupBox.setFlat(True)
        self.accountGroupBox.setObjectName("accountGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.accountGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.messagesBtn = QtWidgets.QPushButton(self.accountGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messagesBtn.sizePolicy().hasHeightForWidth())
        self.messagesBtn.setSizePolicy(sizePolicy)
        self.messagesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.messagesBtn.setObjectName("messagesBtn")
        self.verticalLayout_4.addWidget(self.messagesBtn, 0, QtCore.Qt.AlignLeft)
        self.profileBtn = QtWidgets.QPushButton(self.accountGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileBtn.sizePolicy().hasHeightForWidth())
        self.profileBtn.setSizePolicy(sizePolicy)
        self.profileBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileBtn.setObjectName("profileBtn")
        self.verticalLayout_4.addWidget(self.profileBtn)
        self.sidebar.addWidget(self.accountGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 345, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.sidebar.addItem(spacerItem)
        self.gridLayout.addWidget(self.sidebar_2, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(698, 530))
        self.stackedWidget.setStyleSheet("background-color: rgb(231, 234, 239);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.landingPage = QtWidgets.QWidget()
        self.landingPage.setObjectName("landingPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.landingPage)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.landingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.profileIcon_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileIcon_2.sizePolicy().hasHeightForWidth())
        self.profileIcon_2.setSizePolicy(sizePolicy)
        self.profileIcon_2.setMinimumSize(QtCore.QSize(50, 50))
        self.profileIcon_2.setMaximumSize(QtCore.QSize(50, 50))
        self.profileIcon_2.setText("")
        self.profileIcon_2.setPixmap(QtGui.QPixmap(":/imgs/default-user-icon.jpg"))
        self.profileIcon_2.setScaledContents(True)
        self.profileIcon_2.setObjectName("profileIcon_2")
        self.verticalLayout_9.addWidget(self.profileIcon_2)
        self.storeNameLbl = QtWidgets.QLabel(self.frame_2)
        self.storeNameLbl.setStyleSheet("font: 75 11pt \"Open Sans\";")
        self.storeNameLbl.setObjectName("storeNameLbl")
        self.verticalLayout_9.addWidget(self.storeNameLbl)
        self.customerNameLbl = QtWidgets.QLabel(self.frame_2)
        self.customerNameLbl.setObjectName("customerNameLbl")
        self.verticalLayout_9.addWidget(self.customerNameLbl)
        self.addProductBtn_3 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addProductBtn_3.sizePolicy().hasHeightForWidth())
        self.addProductBtn_3.setSizePolicy(sizePolicy)
        self.addProductBtn_3.setMinimumSize(QtCore.QSize(0, 0))
        self.addProductBtn_3.setMaximumSize(QtCore.QSize(9999, 9999))
        self.addProductBtn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addProductBtn_3.setStyleSheet("QPushButton{border-color: rgb(62, 112, 201);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(62, 112, 201);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:  rgb(62, 112, 201);\n"
"border-color: rgb(255,255,255);\n"
"color: rgb(255,255,255);\n"
"}")
        self.addProductBtn_3.setObjectName("addProductBtn_3")
        self.verticalLayout_9.addWidget(self.addProductBtn_3)
        self.viewCatalogBtn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewCatalogBtn.sizePolicy().hasHeightForWidth())
        self.viewCatalogBtn.setSizePolicy(sizePolicy)
        self.viewCatalogBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.viewCatalogBtn.setMaximumSize(QtCore.QSize(9999, 9999))
        self.viewCatalogBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewCatalogBtn.setStyleSheet("QPushButton{border-color: rgb(65, 184, 105);\n"
"background-color: rgb(65, 184, 105);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:  rgb(72, 206, 117);\n"
"border-color: rgb(255,255,255);\n"
"}")
        self.viewCatalogBtn.setObjectName("viewCatalogBtn")
        self.verticalLayout_9.addWidget(self.viewCatalogBtn)
        self.gridLayout_8.addWidget(self.frame_2, 0, 0, 1, 1)
        self.landingBtnsFrame = QtWidgets.QFrame(self.landingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landingBtnsFrame.sizePolicy().hasHeightForWidth())
        self.landingBtnsFrame.setSizePolicy(sizePolicy)
        self.landingBtnsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.landingBtnsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.landingBtnsFrame.setObjectName("landingBtnsFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.landingBtnsFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.landingOrdersBtn = QtWidgets.QPushButton(self.landingBtnsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landingOrdersBtn.sizePolicy().hasHeightForWidth())
        self.landingOrdersBtn.setSizePolicy(sizePolicy)
        self.landingOrdersBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.landingOrdersBtn.setStyleSheet("QPushButton\n"
"{\n"
"border-color:rgb(243, 65, 53);\n"
"background-color: rgb(243, 65, 53);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"")
        self.landingOrdersBtn.setObjectName("landingOrdersBtn")
        self.gridLayout_7.addWidget(self.landingOrdersBtn, 0, 0, 1, 1)
        self.landingStoreBtn = QtWidgets.QPushButton(self.landingBtnsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landingStoreBtn.sizePolicy().hasHeightForWidth())
        self.landingStoreBtn.setSizePolicy(sizePolicy)
        self.landingStoreBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.landingStoreBtn.setStyleSheet("QPushButton\n"
"{\n"
"border-color: rgb(244, 146, 71);\n"
"background-color: rgb(244, 146, 71);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"")
        self.landingStoreBtn.setObjectName("landingStoreBtn")
        self.gridLayout_7.addWidget(self.landingStoreBtn, 0, 1, 1, 1)
        self.landingRevenueBtn = QtWidgets.QPushButton(self.landingBtnsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landingRevenueBtn.sizePolicy().hasHeightForWidth())
        self.landingRevenueBtn.setSizePolicy(sizePolicy)
        self.landingRevenueBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.landingRevenueBtn.setStyleSheet("QPushButton{border-color: rgb(65, 184, 105);\n"
"background-color: rgb(65, 184, 105);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"")
        self.landingRevenueBtn.setObjectName("landingRevenueBtn")
        self.gridLayout_7.addWidget(self.landingRevenueBtn, 1, 0, 1, 1)
        self.landingProductsBtn = QtWidgets.QPushButton(self.landingBtnsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landingProductsBtn.sizePolicy().hasHeightForWidth())
        self.landingProductsBtn.setSizePolicy(sizePolicy)
        self.landingProductsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.landingProductsBtn.setStyleSheet("QPushButton\n"
"{\n"
"border-color: rgb(63, 112, 199);\n"
"background-color: rgb(63, 112, 199);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"")
        self.landingProductsBtn.setObjectName("landingProductsBtn")
        self.gridLayout_7.addWidget(self.landingProductsBtn, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.landingBtnsFrame, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.landingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(186, 0))
        self.frame_4.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.recentMessagesLbl = QtWidgets.QLabel(self.frame_4)
        self.recentMessagesLbl.setObjectName("recentMessagesLbl")
        self.verticalLayout_10.addWidget(self.recentMessagesLbl)
        self.recentMessagesView = QtWidgets.QListView(self.frame_4)
        self.recentMessagesView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recentMessagesView.setObjectName("recentMessagesView")
        self.verticalLayout_10.addWidget(self.recentMessagesView)
        self.landingMessagesBtn = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landingMessagesBtn.sizePolicy().hasHeightForWidth())
        self.landingMessagesBtn.setSizePolicy(sizePolicy)
        self.landingMessagesBtn.setMinimumSize(QtCore.QSize(0, 20))
        self.landingMessagesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.landingMessagesBtn.setStyleSheet("QPushButton{border-color: rgb(63, 112, 199);\n"
"background-color: rgb(63, 112, 199);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"")
        self.landingMessagesBtn.setObjectName("landingMessagesBtn")
        self.verticalLayout_10.addWidget(self.landingMessagesBtn)
        self.gridLayout_8.addWidget(self.frame_4, 1, 0, 1, 1)
        self.newestListingsFrame = QtWidgets.QFrame(self.landingPage)
        self.newestListingsFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.newestListingsFrame.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.newestListingsFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.newestListingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newestListingsFrame.setObjectName("newestListingsFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.newestListingsFrame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.newestListingsLBL = QtWidgets.QLabel(self.newestListingsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newestListingsLBL.sizePolicy().hasHeightForWidth())
        self.newestListingsLBL.setSizePolicy(sizePolicy)
        self.newestListingsLBL.setStyleSheet("font: 75 16pt \"Open Sans\";")
        self.newestListingsLBL.setObjectName("newestListingsLBL")
        self.verticalLayout_11.addWidget(self.newestListingsLBL)
        self.newProductsGalleryFrame = QtWidgets.QFrame(self.newestListingsFrame)
        self.newProductsGalleryFrame.setStyleSheet("background-color: rgb(231, 234, 239);")
        self.newProductsGalleryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newProductsGalleryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newProductsGalleryFrame.setObjectName("newProductsGalleryFrame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.newProductsGalleryFrame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.newProd1Frame = QtWidgets.QFrame(self.newProductsGalleryFrame)
        self.newProd1Frame.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.newProd1Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newProd1Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newProd1Frame.setObjectName("newProd1Frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.newProd1Frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.prod1imgLbl = QtWidgets.QLabel(self.newProd1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prod1imgLbl.sizePolicy().hasHeightForWidth())
        self.prod1imgLbl.setSizePolicy(sizePolicy)
        self.prod1imgLbl.setMinimumSize(QtCore.QSize(70, 150))
        self.prod1imgLbl.setMaximumSize(QtCore.QSize(150, 150))
        self.prod1imgLbl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prod1imgLbl.setText("")
        self.prod1imgLbl.setPixmap(QtGui.QPixmap(":/imgs/no_photo_use.jpg"))
        self.prod1imgLbl.setScaledContents(True)
        self.prod1imgLbl.setWordWrap(True)
        self.prod1imgLbl.setObjectName("prod1imgLbl")
        self.verticalLayout_12.addWidget(self.prod1imgLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod1titleLbl = QtWidgets.QLabel(self.newProd1Frame)
        self.prod1titleLbl.setObjectName("prod1titleLbl")
        self.verticalLayout_12.addWidget(self.prod1titleLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod1priceLbl = QtWidgets.QLabel(self.newProd1Frame)
        self.prod1priceLbl.setObjectName("prod1priceLbl")
        self.verticalLayout_12.addWidget(self.prod1priceLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod1titleLbl.raise_()
        self.prod1priceLbl.raise_()
        self.prod1imgLbl.raise_()
        self.gridLayout_9.addWidget(self.newProd1Frame, 0, 0, 1, 1)
        self.newProd2Frame = QtWidgets.QFrame(self.newProductsGalleryFrame)
        self.newProd2Frame.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.newProd2Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newProd2Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newProd2Frame.setObjectName("newProd2Frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.newProd2Frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.prod2imgLbl = QtWidgets.QLabel(self.newProd2Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prod2imgLbl.sizePolicy().hasHeightForWidth())
        self.prod2imgLbl.setSizePolicy(sizePolicy)
        self.prod2imgLbl.setMinimumSize(QtCore.QSize(150, 150))
        self.prod2imgLbl.setMaximumSize(QtCore.QSize(150, 150))
        self.prod2imgLbl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prod2imgLbl.setText("")
        self.prod2imgLbl.setPixmap(QtGui.QPixmap(":/imgs/no_photo_use.jpg"))
        self.prod2imgLbl.setScaledContents(True)
        self.prod2imgLbl.setObjectName("prod2imgLbl")
        self.verticalLayout_13.addWidget(self.prod2imgLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod2titleLbl = QtWidgets.QLabel(self.newProd2Frame)
        self.prod2titleLbl.setObjectName("prod2titleLbl")
        self.verticalLayout_13.addWidget(self.prod2titleLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod2priceLbl = QtWidgets.QLabel(self.newProd2Frame)
        self.prod2priceLbl.setObjectName("prod2priceLbl")
        self.verticalLayout_13.addWidget(self.prod2priceLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod2titleLbl.raise_()
        self.prod2priceLbl.raise_()
        self.prod2imgLbl.raise_()
        self.gridLayout_9.addWidget(self.newProd2Frame, 0, 1, 1, 1)
        self.newProd3Frame = QtWidgets.QFrame(self.newProductsGalleryFrame)
        self.newProd3Frame.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.newProd3Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newProd3Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newProd3Frame.setObjectName("newProd3Frame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.newProd3Frame)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.prod3imgLbl = QtWidgets.QLabel(self.newProd3Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prod3imgLbl.sizePolicy().hasHeightForWidth())
        self.prod3imgLbl.setSizePolicy(sizePolicy)
        self.prod3imgLbl.setMinimumSize(QtCore.QSize(150, 150))
        self.prod3imgLbl.setMaximumSize(QtCore.QSize(150, 150))
        self.prod3imgLbl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prod3imgLbl.setText("")
        self.prod3imgLbl.setPixmap(QtGui.QPixmap(":/imgs/no_photo_use.jpg"))
        self.prod3imgLbl.setScaledContents(True)
        self.prod3imgLbl.setObjectName("prod3imgLbl")
        self.verticalLayout_15.addWidget(self.prod3imgLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod3titleLbl = QtWidgets.QLabel(self.newProd3Frame)
        self.prod3titleLbl.setObjectName("prod3titleLbl")
        self.verticalLayout_15.addWidget(self.prod3titleLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod3priceLbl = QtWidgets.QLabel(self.newProd3Frame)
        self.prod3priceLbl.setObjectName("prod3priceLbl")
        self.verticalLayout_15.addWidget(self.prod3priceLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod3titleLbl.raise_()
        self.prod3priceLbl.raise_()
        self.prod3imgLbl.raise_()
        self.gridLayout_9.addWidget(self.newProd3Frame, 1, 0, 1, 1)
        self.newProd4Frame = QtWidgets.QFrame(self.newProductsGalleryFrame)
        self.newProd4Frame.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.newProd4Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newProd4Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newProd4Frame.setObjectName("newProd4Frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.newProd4Frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.prod4imgLbl = QtWidgets.QLabel(self.newProd4Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prod4imgLbl.sizePolicy().hasHeightForWidth())
        self.prod4imgLbl.setSizePolicy(sizePolicy)
        self.prod4imgLbl.setMinimumSize(QtCore.QSize(150, 150))
        self.prod4imgLbl.setMaximumSize(QtCore.QSize(150, 150))
        self.prod4imgLbl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prod4imgLbl.setText("")
        self.prod4imgLbl.setPixmap(QtGui.QPixmap(":/imgs/no_photo_use.jpg"))
        self.prod4imgLbl.setScaledContents(True)
        self.prod4imgLbl.setObjectName("prod4imgLbl")
        self.verticalLayout_14.addWidget(self.prod4imgLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod4titleLbl = QtWidgets.QLabel(self.newProd4Frame)
        self.prod4titleLbl.setObjectName("prod4titleLbl")
        self.verticalLayout_14.addWidget(self.prod4titleLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod4priceLbl = QtWidgets.QLabel(self.newProd4Frame)
        self.prod4priceLbl.setObjectName("prod4priceLbl")
        self.verticalLayout_14.addWidget(self.prod4priceLbl, 0, QtCore.Qt.AlignHCenter)
        self.prod4titleLbl.raise_()
        self.prod4priceLbl.raise_()
        self.prod4imgLbl.raise_()
        self.gridLayout_9.addWidget(self.newProd4Frame, 1, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.newProductsGalleryFrame)
        self.newestListingsBtn = QtWidgets.QPushButton(self.newestListingsFrame)
        self.newestListingsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newestListingsBtn.setStyleSheet("QPushButton{border-color: rgb(63, 112, 199);\n"
"background-color: rgb(63, 112, 199);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"")
        self.newestListingsBtn.setObjectName("newestListingsBtn")
        self.verticalLayout_11.addWidget(self.newestListingsBtn)
        self.gridLayout_8.addWidget(self.newestListingsFrame, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.landingPage)
        self.ordersPage = QtWidgets.QWidget()
        self.ordersPage.setObjectName("ordersPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ordersPage)
        self.gridLayout_3.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.orderhistoryLbl = QtWidgets.QLabel(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderhistoryLbl.sizePolicy().hasHeightForWidth())
        self.orderhistoryLbl.setSizePolicy(sizePolicy)
        self.orderhistoryLbl.setObjectName("orderhistoryLbl")
        self.gridLayout_3.addWidget(self.orderhistoryLbl, 0, 0, 1, 1)
        self.showLbl = QtWidgets.QLabel(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showLbl.sizePolicy().hasHeightForWidth())
        self.showLbl.setSizePolicy(sizePolicy)
        self.showLbl.setObjectName("showLbl")
        self.gridLayout_3.addWidget(self.showLbl, 1, 0, 1, 1)
        self.orderTable = QtWidgets.QTableView(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderTable.sizePolicy().hasHeightForWidth())
        self.orderTable.setSizePolicy(sizePolicy)
        self.orderTable.setMinimumSize(QtCore.QSize(0, 0))
        self.orderTable.setStyleSheet("alternate-background-color: rgb(241, 241, 241);\n"
"background-color: rgb(255, 255, 255);")
        self.orderTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.orderTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.orderTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.orderTable.setAlternatingRowColors(True)
        self.orderTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.orderTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.orderTable.setSortingEnabled(True)
        self.orderTable.setWordWrap(False)
        self.orderTable.setCornerButtonEnabled(False)
        self.orderTable.setObjectName("orderTable")
        self.orderTable.horizontalHeader().setCascadingSectionResizes(True)
        self.orderTable.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.orderTable, 4, 0, 1, 3)
        self.showCombo = QtWidgets.QComboBox(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showCombo.sizePolicy().hasHeightForWidth())
        self.showCombo.setSizePolicy(sizePolicy)
        self.showCombo.setMinimumSize(QtCore.QSize(81, 20))
        self.showCombo.setMaximumSize(QtCore.QSize(158, 20))
        self.showCombo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.showCombo.setObjectName("showCombo")
        self.showCombo.addItem("")
        self.showCombo.addItem("")
        self.showCombo.addItem("")
        self.showCombo.addItem("")
        self.gridLayout_3.addWidget(self.showCombo, 2, 0, 1, 1)
        self.searchLbl = QtWidgets.QLabel(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLbl.sizePolicy().hasHeightForWidth())
        self.searchLbl.setSizePolicy(sizePolicy)
        self.searchLbl.setObjectName("searchLbl")
        self.gridLayout_3.addWidget(self.searchLbl, 1, 2, 1, 1)
        self.orderSearchLE = QtWidgets.QLineEdit(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderSearchLE.sizePolicy().hasHeightForWidth())
        self.orderSearchLE.setSizePolicy(sizePolicy)
        self.orderSearchLE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.orderSearchLE.setObjectName("orderSearchLE")
        self.gridLayout_3.addWidget(self.orderSearchLE, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.ordersPage)
        self.inboxPage = QtWidgets.QWidget()
        self.inboxPage.setObjectName("inboxPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.inboxPage)
        self.gridLayout_2.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.inboxPage)
        self.frame.setMaximumSize(QtCore.QSize(95, 137))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inboxBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inboxBtn.sizePolicy().hasHeightForWidth())
        self.inboxBtn.setSizePolicy(sizePolicy)
        self.inboxBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inboxBtn.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.inboxBtn.setObjectName("inboxBtn")
        self.verticalLayout.addWidget(self.inboxBtn)
        self.unreadBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unreadBtn.sizePolicy().hasHeightForWidth())
        self.unreadBtn.setSizePolicy(sizePolicy)
        self.unreadBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.unreadBtn.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.unreadBtn.setObjectName("unreadBtn")
        self.verticalLayout.addWidget(self.unreadBtn)
        self.sentBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentBtn.sizePolicy().hasHeightForWidth())
        self.sentBtn.setSizePolicy(sizePolicy)
        self.sentBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sentBtn.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.sentBtn.setObjectName("sentBtn")
        self.verticalLayout.addWidget(self.sentBtn)
        self.trashBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trashBtn.sizePolicy().hasHeightForWidth())
        self.trashBtn.setSizePolicy(sizePolicy)
        self.trashBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trashBtn.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.trashBtn.setObjectName("trashBtn")
        self.verticalLayout.addWidget(self.trashBtn)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.inboxLbl = QtWidgets.QLabel(self.inboxPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inboxLbl.sizePolicy().hasHeightForWidth())
        self.inboxLbl.setSizePolicy(sizePolicy)
        self.inboxLbl.setTextFormat(QtCore.Qt.AutoText)
        self.inboxLbl.setObjectName("inboxLbl")
        self.gridLayout_2.addWidget(self.inboxLbl, 0, 0, 1, 1)
        self.inboxStackedWidget = QtWidgets.QStackedWidget(self.inboxPage)
        self.inboxStackedWidget.setObjectName("inboxStackedWidget")
        self.inboxTablePage = QtWidgets.QWidget()
        self.inboxTablePage.setObjectName("inboxTablePage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.inboxTablePage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.inboxTable = QtWidgets.QTableView(self.inboxTablePage)
        self.inboxTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inboxTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inboxTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.inboxTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.inboxTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.inboxTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.inboxTable.setShowGrid(False)
        self.inboxTable.setObjectName("inboxTable")
        self.inboxTable.horizontalHeader().setVisible(False)
        self.inboxTable.horizontalHeader().setCascadingSectionResizes(False)
        self.inboxTable.horizontalHeader().setHighlightSections(False)
        self.inboxTable.horizontalHeader().setStretchLastSection(True)
        self.inboxTable.verticalHeader().setVisible(False)
        self.inboxTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_5.addWidget(self.inboxTable)
        self.inboxStackedWidget.addWidget(self.inboxTablePage)
        self.unreadTablePage = QtWidgets.QWidget()
        self.unreadTablePage.setObjectName("unreadTablePage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.unreadTablePage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.unreadTable = QtWidgets.QTableView(self.unreadTablePage)
        self.unreadTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.unreadTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.unreadTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.unreadTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.unreadTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.unreadTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.unreadTable.setShowGrid(False)
        self.unreadTable.setObjectName("unreadTable")
        self.unreadTable.horizontalHeader().setVisible(False)
        self.unreadTable.horizontalHeader().setCascadingSectionResizes(False)
        self.unreadTable.horizontalHeader().setHighlightSections(False)
        self.unreadTable.verticalHeader().setVisible(False)
        self.unreadTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_6.addWidget(self.unreadTable)
        self.inboxStackedWidget.addWidget(self.unreadTablePage)
        self.sentTablePage = QtWidgets.QWidget()
        self.sentTablePage.setObjectName("sentTablePage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sentTablePage)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sentTable = QtWidgets.QTableView(self.sentTablePage)
        self.sentTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sentTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sentTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.sentTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sentTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.sentTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sentTable.setShowGrid(False)
        self.sentTable.setObjectName("sentTable")
        self.sentTable.horizontalHeader().setVisible(False)
        self.sentTable.horizontalHeader().setCascadingSectionResizes(False)
        self.sentTable.horizontalHeader().setHighlightSections(False)
        self.sentTable.verticalHeader().setVisible(False)
        self.sentTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_7.addWidget(self.sentTable)
        self.inboxStackedWidget.addWidget(self.sentTablePage)
        self.trashTablePage = QtWidgets.QWidget()
        self.trashTablePage.setObjectName("trashTablePage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.trashTablePage)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.trashTable = QtWidgets.QTableView(self.trashTablePage)
        self.trashTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.trashTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.trashTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.trashTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.trashTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.trashTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.trashTable.setShowGrid(False)
        self.trashTable.setObjectName("trashTable")
        self.trashTable.horizontalHeader().setVisible(False)
        self.trashTable.horizontalHeader().setCascadingSectionResizes(False)
        self.trashTable.horizontalHeader().setHighlightSections(False)
        self.trashTable.verticalHeader().setVisible(False)
        self.trashTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_8.addWidget(self.trashTable)
        self.inboxStackedWidget.addWidget(self.trashTablePage)
        self.gridLayout_2.addWidget(self.inboxStackedWidget, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.inboxPage)
        self.catalogPage = QtWidgets.QWidget()
        self.catalogPage.setObjectName("catalogPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.catalogPage)
        self.gridLayout_4.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.categoryCombo = QtWidgets.QComboBox(self.catalogPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryCombo.sizePolicy().hasHeightForWidth())
        self.categoryCombo.setSizePolicy(sizePolicy)
        self.categoryCombo.setMinimumSize(QtCore.QSize(81, 20))
        self.categoryCombo.setMaximumSize(QtCore.QSize(158, 20))
        self.categoryCombo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.categoryCombo.setObjectName("categoryCombo")
        self.gridLayout_4.addWidget(self.categoryCombo, 2, 0, 1, 1)
        self.catalogTable = QtWidgets.QTableView(self.catalogPage)
        self.catalogTable.setStyleSheet("alternate-background-color: rgb(241, 241, 241);\n"
"background-color: rgb(255, 255, 255);")
        self.catalogTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.catalogTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.catalogTable.setSortingEnabled(True)
        self.catalogTable.setObjectName("catalogTable")
        self.catalogTable.horizontalHeader().setCascadingSectionResizes(True)
        self.catalogTable.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.catalogTable, 3, 0, 1, 3)
        self.catLbl = QtWidgets.QLabel(self.catalogPage)
        self.catLbl.setObjectName("catLbl")
        self.gridLayout_4.addWidget(self.catLbl, 1, 0, 1, 1)
        self.addProductBtn = QtWidgets.QPushButton(self.catalogPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addProductBtn.sizePolicy().hasHeightForWidth())
        self.addProductBtn.setSizePolicy(sizePolicy)
        self.addProductBtn.setMinimumSize(QtCore.QSize(81, 20))
        self.addProductBtn.setMaximumSize(QtCore.QSize(111, 20))
        self.addProductBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addProductBtn.setStyleSheet("QPushButton{border-color: rgb(62, 112, 201);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(62, 112, 201);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:  rgb(62, 112, 201);\n"
"border-color: rgb(255,255,255);\n"
"color: rgb(255,255,255);\n"
"}")
        self.addProductBtn.setObjectName("addProductBtn")
        self.gridLayout_4.addWidget(self.addProductBtn, 2, 2, 1, 1)
        self.productCatalogLbl = QtWidgets.QLabel(self.catalogPage)
        self.productCatalogLbl.setObjectName("productCatalogLbl")
        self.gridLayout_4.addWidget(self.productCatalogLbl, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.catalogPage)
        self.pendingPage = QtWidgets.QWidget()
        self.pendingPage.setObjectName("pendingPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pendingPage)
        self.gridLayout_5.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pendCatLbl = QtWidgets.QLabel(self.pendingPage)
        self.pendCatLbl.setObjectName("pendCatLbl")
        self.gridLayout_5.addWidget(self.pendCatLbl, 1, 0, 1, 1)
        self.pendCatCombo = QtWidgets.QComboBox(self.pendingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pendCatCombo.sizePolicy().hasHeightForWidth())
        self.pendCatCombo.setSizePolicy(sizePolicy)
        self.pendCatCombo.setMinimumSize(QtCore.QSize(81, 20))
        self.pendCatCombo.setMaximumSize(QtCore.QSize(158, 20))
        self.pendCatCombo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pendCatCombo.setObjectName("pendCatCombo")
        self.gridLayout_5.addWidget(self.pendCatCombo, 2, 0, 1, 1)
        self.pendTable = QtWidgets.QTableView(self.pendingPage)
        self.pendTable.setStyleSheet("alternate-background-color: rgb(241, 241, 241);\n"
"background-color: rgb(255, 255, 255);")
        self.pendTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.pendTable.setSortingEnabled(True)
        self.pendTable.setObjectName("pendTable")
        self.pendTable.horizontalHeader().setCascadingSectionResizes(True)
        self.pendTable.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.pendTable, 3, 0, 1, 3)
        self.addPendProdBtn = QtWidgets.QPushButton(self.pendingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPendProdBtn.sizePolicy().hasHeightForWidth())
        self.addPendProdBtn.setSizePolicy(sizePolicy)
        self.addPendProdBtn.setMinimumSize(QtCore.QSize(81, 20))
        self.addPendProdBtn.setMaximumSize(QtCore.QSize(111, 20))
        self.addPendProdBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addPendProdBtn.setStyleSheet("QPushButton{border-color: rgb(62, 112, 201);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(62, 112, 201);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:  rgb(62, 112, 201);\n"
"border-color: rgb(255,255,255);\n"
"color: rgb(255,255,255);\n"
"}")
        self.addPendProdBtn.setObjectName("addPendProdBtn")
        self.gridLayout_5.addWidget(self.addPendProdBtn, 2, 2, 1, 1)
        self.pendUploadsLbl = QtWidgets.QLabel(self.pendingPage)
        self.pendUploadsLbl.setObjectName("pendUploadsLbl")
        self.gridLayout_5.addWidget(self.pendUploadsLbl, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pendingPage)
        self.profilePage = QtWidgets.QWidget()
        self.profilePage.setObjectName("profilePage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.profilePage)
        self.gridLayout_6.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.changeIconBtn = QtWidgets.QPushButton(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeIconBtn.sizePolicy().hasHeightForWidth())
        self.changeIconBtn.setSizePolicy(sizePolicy)
        self.changeIconBtn.setMinimumSize(QtCore.QSize(80, 22))
        self.changeIconBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changeIconBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(63, 112, 199);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"alternate-background-color: rgb(50, 90, 159);\n"
"}\n"
"QPushButton:pressed \n"
"{\n"
"background-color:rgb(255,255,255);\n"
"color: rgb(63,112,199);\n"
"}")
        self.changeIconBtn.setObjectName("changeIconBtn")
        self.gridLayout_6.addWidget(self.changeIconBtn, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 11, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.profilePage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 10, 0, 1, 1)
        self.paypalEmailLE = QtWidgets.QLineEdit(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paypalEmailLE.sizePolicy().hasHeightForWidth())
        self.paypalEmailLE.setSizePolicy(sizePolicy)
        self.paypalEmailLE.setMinimumSize(QtCore.QSize(300, 0))
        self.paypalEmailLE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.paypalEmailLE.setObjectName("paypalEmailLE")
        self.gridLayout_6.addWidget(self.paypalEmailLE, 7, 0, 1, 5)
        self.profileIcon = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileIcon.sizePolicy().hasHeightForWidth())
        self.profileIcon.setSizePolicy(sizePolicy)
        self.profileIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.profileIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.profileIcon.setText("")
        self.profileIcon.setPixmap(QtGui.QPixmap(":/imgs/default-user-icon.jpg"))
        self.profileIcon.setScaledContents(True)
        self.profileIcon.setObjectName("profileIcon")
        self.gridLayout_6.addWidget(self.profileIcon, 2, 0, 1, 1)
        self.profileDescTE = QtWidgets.QTextEdit(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileDescTE.sizePolicy().hasHeightForWidth())
        self.profileDescTE.setSizePolicy(sizePolicy)
        self.profileDescTE.setMinimumSize(QtCore.QSize(0, 0))
        self.profileDescTE.setMaximumSize(QtCore.QSize(999999, 200))
        self.profileDescTE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.profileDescTE.setObjectName("profileDescTE")
        self.gridLayout_6.addWidget(self.profileDescTE, 5, 0, 1, 1)
        self.emailconfidLbl = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailconfidLbl.sizePolicy().hasHeightForWidth())
        self.emailconfidLbl.setSizePolicy(sizePolicy)
        self.emailconfidLbl.setObjectName("emailconfidLbl")
        self.gridLayout_6.addWidget(self.emailconfidLbl, 8, 0, 1, 1)
        self.paypalEmailLbl = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paypalEmailLbl.sizePolicy().hasHeightForWidth())
        self.paypalEmailLbl.setSizePolicy(sizePolicy)
        self.paypalEmailLbl.setObjectName("paypalEmailLbl")
        self.gridLayout_6.addWidget(self.paypalEmailLbl, 6, 0, 1, 1)
        self.profileDescLbl = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileDescLbl.sizePolicy().hasHeightForWidth())
        self.profileDescLbl.setSizePolicy(sizePolicy)
        self.profileDescLbl.setObjectName("profileDescLbl")
        self.gridLayout_6.addWidget(self.profileDescLbl, 4, 0, 1, 1)
        self.profileLbl = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileLbl.sizePolicy().hasHeightForWidth())
        self.profileLbl.setSizePolicy(sizePolicy)
        self.profileLbl.setObjectName("profileLbl")
        self.gridLayout_6.addWidget(self.profileLbl, 0, 0, 1, 1)
        self.profileSaveBtn = QtWidgets.QPushButton(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileSaveBtn.sizePolicy().hasHeightForWidth())
        self.profileSaveBtn.setSizePolicy(sizePolicy)
        self.profileSaveBtn.setMinimumSize(QtCore.QSize(90, 25))
        self.profileSaveBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileSaveBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(63, 112, 199);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"alternate-background-color: rgb(50, 90, 159);\n"
"}\n"
"QPushButton:pressed \n"
"{\n"
"background-color:rgb(255,255,255);\n"
"color: rgb(63,112,199);\n"
"}")
        self.profileSaveBtn.setFlat(False)
        self.profileSaveBtn.setObjectName("profileSaveBtn")
        self.gridLayout_6.addWidget(self.profileSaveBtn, 9, 0, 1, 1)
        self.stackedWidget.addWidget(self.profilePage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        HSMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HSMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuLoad = QtWidgets.QMenu(self.menuFile)
        self.menuLoad.setObjectName("menuLoad")
        self.menuExport_CSV = QtWidgets.QMenu(self.menuFile)
        self.menuExport_CSV.setObjectName("menuExport_CSV")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        HSMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HSMainWindow)
        self.statusbar.setObjectName("statusbar")
        HSMainWindow.setStatusBar(self.statusbar)
        self.actionNewItem = QtWidgets.QAction(HSMainWindow)
        self.actionNewItem.setObjectName("actionNewItem")
        self.actionTemplate = QtWidgets.QAction(HSMainWindow)
        self.actionTemplate.setObjectName("actionTemplate")
        self.actionClose = QtWidgets.QAction(HSMainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAll_Items = QtWidgets.QAction(HSMainWindow)
        self.actionAll_Items.setObjectName("actionAll_Items")
        self.actionCheck_for_New_Items = QtWidgets.QAction(HSMainWindow)
        self.actionCheck_for_New_Items.setObjectName("actionCheck_for_New_Items")
        self.actionUpload_Waiting_Items = QtWidgets.QAction(HSMainWindow)
        self.actionUpload_Waiting_Items.setObjectName("actionUpload_Waiting_Items")
        self.showAbout = QtWidgets.QAction(HSMainWindow)
        self.showAbout.setObjectName("showAbout")
        self.actionInventory_CSV = QtWidgets.QAction(HSMainWindow)
        self.actionInventory_CSV.setObjectName("actionInventory_CSV")
        self.actionActive_Catalog = QtWidgets.QAction(HSMainWindow)
        self.actionActive_Catalog.setObjectName("actionActive_Catalog")
        self.actionInactive_Items = QtWidgets.QAction(HSMainWindow)
        self.actionInactive_Items.setObjectName("actionInactive_Items")
        self.actionGlobal_Catalog = QtWidgets.QAction(HSMainWindow)
        self.actionGlobal_Catalog.setObjectName("actionGlobal_Catalog")
        self.actionProductCatalogCSV = QtWidgets.QAction(HSMainWindow)
        self.actionProductCatalogCSV.setObjectName("actionProductCatalogCSV")
        self.actionHelpGuide = QtWidgets.QAction(HSMainWindow)
        self.actionHelpGuide.setObjectName("actionHelpGuide")
        self.actionAbout = QtWidgets.QAction(HSMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuNew.addAction(self.actionNewItem)
        self.menuLoad.addAction(self.actionInventory_CSV)
        self.menuExport_CSV.addAction(self.actionProductCatalogCSV)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addAction(self.menuExport_CSV.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionHelpGuide)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HSMainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.inboxStackedWidget.setCurrentIndex(0)
        self.ordersBtn.clicked.connect(HSMainWindow.initOrdersView)
        self.messagesBtn.clicked.connect(HSMainWindow.initInboxView)
        self.productsBtn.clicked.connect(HSMainWindow.initProductsView)
        self.pendBtn.clicked.connect(HSMainWindow.initPendingView)
        self.profileBtn.clicked.connect(HSMainWindow.initProfileView)
        self.addProductBtn_2.clicked.connect(HSMainWindow.addProduct)
        self.landingBtn.clicked.connect(HSMainWindow.initLandingView)
        self.changeIconBtn.clicked.connect(HSMainWindow.changeProfileIcon)
        self.trashBtn.clicked.connect(HSMainWindow.switchTrashTable)
        self.unreadBtn.clicked.connect(HSMainWindow.switchUnreadTable)
        self.showCombo.currentIndexChanged['QString'].connect(HSMainWindow.changeOrderTableLength)
        self.viewCatalogBtn.clicked.connect(HSMainWindow.initProductsView)
        self.addProductBtn_3.clicked.connect(HSMainWindow.addProduct)
        self.pendCatCombo.currentIndexChanged['QString'].connect(HSMainWindow.filterPendingProductsTable)
        self.orderSearchLE.textEdited['QString'].connect(HSMainWindow.searchOrderTable)
        self.landingOrdersBtn.clicked.connect(HSMainWindow.initOrdersView)
        self.categoryCombo.currentIndexChanged['QString'].connect(HSMainWindow.filterProductsTable)
        self.addPendProdBtn.clicked.connect(HSMainWindow.addProduct)
        self.addProductBtn.clicked.connect(HSMainWindow.addProduct)
        self.profileSaveBtn.clicked.connect(HSMainWindow.saveProfileChanges)
        self.landingRevenueBtn.clicked.connect(HSMainWindow.initOrdersView)
        self.inboxBtn.clicked.connect(HSMainWindow.switchInboxTable)
        self.sentBtn.clicked.connect(HSMainWindow.switchSentTable)
        self.landingMessagesBtn.clicked.connect(HSMainWindow.initInboxView)
        self.newestListingsBtn.clicked.connect(HSMainWindow.initNewProductsView)
        self.landingProductsBtn.clicked.connect(HSMainWindow.initProductsView)
        self.landingStoreBtn.clicked.connect(HSMainWindow.initStorePageView)
        QtCore.QMetaObject.connectSlotsByName(HSMainWindow)
        HSMainWindow.setTabOrder(self.addProductBtn_2, self.productsBtn)
        HSMainWindow.setTabOrder(self.productsBtn, self.pendBtn)
        HSMainWindow.setTabOrder(self.pendBtn, self.ordersBtn)
        HSMainWindow.setTabOrder(self.ordersBtn, self.messagesBtn)
        HSMainWindow.setTabOrder(self.messagesBtn, self.profileBtn)
        HSMainWindow.setTabOrder(self.profileBtn, self.inboxBtn)
        HSMainWindow.setTabOrder(self.inboxBtn, self.unreadBtn)
        HSMainWindow.setTabOrder(self.unreadBtn, self.sentBtn)
        HSMainWindow.setTabOrder(self.sentBtn, self.trashBtn)

    def retranslateUi(self, HSMainWindow):
        _translate = QtCore.QCoreApplication.translate
        HSMainWindow.setWindowTitle(_translate("HSMainWindow", "HangarSwap Seller App"))
        self.label.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Home</span></p></body></html>"))
        self.landingBtn.setToolTip(_translate("HSMainWindow", "<html><head/><body><p>App Main Page</p></body></html>"))
        self.catalogGroupBox.setTitle(_translate("HSMainWindow", "Catalog"))
        self.addProductBtn_2.setToolTip(_translate("HSMainWindow", "<html><head/><body><p>Add a New Product</p></body></html>"))
        self.addProductBtn_2.setText(_translate("HSMainWindow", "Add Product"))
        self.productsBtn.setToolTip(_translate("HSMainWindow", "<html><head/><body><p>Active HangarSwap Listings</p></body></html>"))
        self.productsBtn.setText(_translate("HSMainWindow", "Products"))
        self.pendBtn.setToolTip(_translate("HSMainWindow", "<html><head/><body><p>Products Not Yet Uploaded</p></body></html>"))
        self.pendBtn.setText(_translate("HSMainWindow", "Waiting to Upload"))
        self.salesGroupBox.setTitle(_translate("HSMainWindow", "Sales"))
        self.ordersBtn.setToolTip(_translate("HSMainWindow", "<html><head/><body><p>Sales History</p></body></html>"))
        self.ordersBtn.setText(_translate("HSMainWindow", "Order History"))
        self.accountGroupBox.setTitle(_translate("HSMainWindow", "My Account"))
        self.messagesBtn.setToolTip(_translate("HSMainWindow", "<html><head/><body><p>My Messages</p></body></html>"))
        self.messagesBtn.setText(_translate("HSMainWindow", "Messages"))
        self.profileBtn.setToolTip(_translate("HSMainWindow", "<html><head/><body><p>My HangarSwap Profile</p></body></html>"))
        self.profileBtn.setText(_translate("HSMainWindow", "Profile"))
        self.storeNameLbl.setText(_translate("HSMainWindow", "Store Name"))
        self.customerNameLbl.setText(_translate("HSMainWindow", "Customer Name"))
        self.addProductBtn_3.setText(_translate("HSMainWindow", "Add Product +"))
        self.viewCatalogBtn.setText(_translate("HSMainWindow", "View My Catalog"))
        self.landingOrdersBtn.setText(_translate("HSMainWindow", "Orders"))
        self.landingStoreBtn.setText(_translate("HSMainWindow", "View My Store"))
        self.landingRevenueBtn.setText(_translate("HSMainWindow", "Revenue"))
        self.landingProductsBtn.setText(_translate("HSMainWindow", "Products"))
        self.recentMessagesLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Recent Messages</span></p></body></html>"))
        self.landingMessagesBtn.setText(_translate("HSMainWindow", "View All Messages"))
        self.newestListingsLBL.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Newest Listings</span></p></body></html>"))
        self.prod1titleLbl.setText(_translate("HSMainWindow", "PROD 1 TITLE"))
        self.prod1priceLbl.setText(_translate("HSMainWindow", "PROD 1 PRICE"))
        self.prod2titleLbl.setText(_translate("HSMainWindow", "PROD 2 TITLE"))
        self.prod2priceLbl.setText(_translate("HSMainWindow", "PROD 2 PRICE"))
        self.prod3titleLbl.setText(_translate("HSMainWindow", "PROD 3 TITLE"))
        self.prod3priceLbl.setText(_translate("HSMainWindow", "PROD 3 PRICE"))
        self.prod4titleLbl.setText(_translate("HSMainWindow", "PROD 4 TITLE"))
        self.prod4priceLbl.setText(_translate("HSMainWindow", "PROD 4 PRICE"))
        self.newestListingsBtn.setText(_translate("HSMainWindow", "View Newest Items on HangarSwap.com"))
        self.orderhistoryLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Order History</span></p></body></html>"))
        self.showLbl.setText(_translate("HSMainWindow", "Show:"))
        self.showCombo.setItemText(0, _translate("HSMainWindow", "10"))
        self.showCombo.setItemText(1, _translate("HSMainWindow", "25"))
        self.showCombo.setItemText(2, _translate("HSMainWindow", "50"))
        self.showCombo.setItemText(3, _translate("HSMainWindow", "100"))
        self.searchLbl.setText(_translate("HSMainWindow", "Search:"))
        self.inboxBtn.setText(_translate("HSMainWindow", "Inbox"))
        self.unreadBtn.setText(_translate("HSMainWindow", "Unread"))
        self.sentBtn.setText(_translate("HSMainWindow", "Sent"))
        self.trashBtn.setText(_translate("HSMainWindow", "Trash"))
        self.inboxLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Inbox</span></p></body></html>"))
        self.catLbl.setText(_translate("HSMainWindow", "Category Filter:"))
        self.addProductBtn.setText(_translate("HSMainWindow", "Add Product +"))
        self.productCatalogLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Product Catalog</span></p></body></html>"))
        self.pendCatLbl.setText(_translate("HSMainWindow", "Category Filter:"))
        self.addPendProdBtn.setText(_translate("HSMainWindow", "Add Product +"))
        self.pendUploadsLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Pending Uploads</span></p></body></html>"))
        self.changeIconBtn.setText(_translate("HSMainWindow", "Change Icon"))
        self.emailconfidLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#515558;\">We\'ll never share your email with anyone else.</span></p></body></html>"))
        self.paypalEmailLbl.setText(_translate("HSMainWindow", "Paypal Email Address"))
        self.profileDescLbl.setText(_translate("HSMainWindow", "Seller Profile Description"))
        self.profileLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">My Seller Profile</span></p></body></html>"))
        self.profileSaveBtn.setText(_translate("HSMainWindow", "Save Changes"))
        self.menuFile.setTitle(_translate("HSMainWindow", "File"))
        self.menuNew.setTitle(_translate("HSMainWindow", "New"))
        self.menuLoad.setTitle(_translate("HSMainWindow", "Import"))
        self.menuExport_CSV.setTitle(_translate("HSMainWindow", "Export"))
        self.menuHelp.setTitle(_translate("HSMainWindow", "Help"))
        self.actionNewItem.setText(_translate("HSMainWindow", "Item"))
        self.actionTemplate.setText(_translate("HSMainWindow", "Template"))
        self.actionClose.setText(_translate("HSMainWindow", "Close"))
        self.actionAll_Items.setText(_translate("HSMainWindow", "All Items"))
        self.actionCheck_for_New_Items.setText(_translate("HSMainWindow", "Check for New Items"))
        self.actionUpload_Waiting_Items.setText(_translate("HSMainWindow", "Upload Waiting Items"))
        self.showAbout.setText(_translate("HSMainWindow", "About"))
        self.actionInventory_CSV.setText(_translate("HSMainWindow", "Inventory Catalog (CSV)"))
        self.actionActive_Catalog.setText(_translate("HSMainWindow", "Active"))
        self.actionInactive_Items.setText(_translate("HSMainWindow", "Inactive"))
        self.actionGlobal_Catalog.setText(_translate("HSMainWindow", "Global Catalog"))
        self.actionProductCatalogCSV.setText(_translate("HSMainWindow", "Product Catalog (CSV)"))
        self.actionHelpGuide.setText(_translate("HSMainWindow", "Help Guide"))
        self.actionAbout.setText(_translate("HSMainWindow", "About"))

import RESOURCES
