# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_redesign.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HSMainWindow(object):
    def setupUi(self, HSMainWindow):
        HSMainWindow.setObjectName("HSMainWindow")
        HSMainWindow.resize(849, 632)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HSMainWindow.sizePolicy().hasHeightForWidth())
        HSMainWindow.setSizePolicy(sizePolicy)
        HSMainWindow.setMinimumSize(QtCore.QSize(849, 632))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        HSMainWindow.setFont(font)
        HSMainWindow.setMouseTracking(True)
        HSMainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        HSMainWindow.setStyleSheet("QMenuBar {\n"
"    background-color: rgb(54, 56, 67);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        HSMainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        HSMainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(HSMainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sidebar_2 = QtWidgets.QFrame(self.centralwidget)
        self.sidebar_2.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"font: 8pt \"Open Sans\";\n"
"QPushButton {cursor:\"Pointing Hand\";}")
        self.sidebar_2.setObjectName("sidebar_2")
        self.sidebar = QtWidgets.QVBoxLayout(self.sidebar_2)
        self.sidebar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.sidebar.setSpacing(0)
        self.sidebar.setObjectName("sidebar")
        self.catalogGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catalogGroupBox.sizePolicy().hasHeightForWidth())
        self.catalogGroupBox.setSizePolicy(sizePolicy)
        self.catalogGroupBox.setFlat(True)
        self.catalogGroupBox.setObjectName("catalogGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.catalogGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.productsBtn = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productsBtn.sizePolicy().hasHeightForWidth())
        self.productsBtn.setSizePolicy(sizePolicy)
        self.productsBtn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.productsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.productsBtn.setStyleSheet("")
        self.productsBtn.setCheckable(False)
        self.productsBtn.setAutoExclusive(True)
        self.productsBtn.setFlat(False)
        self.productsBtn.setObjectName("productsBtn")
        self.verticalLayout_2.addWidget(self.productsBtn)
        self.pendBtn = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pendBtn.sizePolicy().hasHeightForWidth())
        self.pendBtn.setSizePolicy(sizePolicy)
        self.pendBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pendBtn.setObjectName("pendBtn")
        self.main_view_group = QtWidgets.QButtonGroup(HSMainWindow)
        self.main_view_group.setObjectName("main_view_group")
        self.main_view_group.addButton(self.pendBtn)
        self.verticalLayout_2.addWidget(self.pendBtn)
        self.sidebar.addWidget(self.catalogGroupBox)
        self.salesGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salesGroupBox.sizePolicy().hasHeightForWidth())
        self.salesGroupBox.setSizePolicy(sizePolicy)
        self.salesGroupBox.setFlat(True)
        self.salesGroupBox.setObjectName("salesGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.salesGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ordersBtn = QtWidgets.QPushButton(self.salesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ordersBtn.sizePolicy().hasHeightForWidth())
        self.ordersBtn.setSizePolicy(sizePolicy)
        self.ordersBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ordersBtn.setObjectName("ordersBtn")
        self.verticalLayout_3.addWidget(self.ordersBtn)
        self.sidebar.addWidget(self.salesGroupBox)
        self.accountGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountGroupBox.sizePolicy().hasHeightForWidth())
        self.accountGroupBox.setSizePolicy(sizePolicy)
        self.accountGroupBox.setFlat(True)
        self.accountGroupBox.setObjectName("accountGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.accountGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.messagesBtn = QtWidgets.QPushButton(self.accountGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messagesBtn.sizePolicy().hasHeightForWidth())
        self.messagesBtn.setSizePolicy(sizePolicy)
        self.messagesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.messagesBtn.setObjectName("messagesBtn")
        self.verticalLayout_4.addWidget(self.messagesBtn, 0, QtCore.Qt.AlignLeft)
        self.profileBtn = QtWidgets.QPushButton(self.accountGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileBtn.sizePolicy().hasHeightForWidth())
        self.profileBtn.setSizePolicy(sizePolicy)
        self.profileBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileBtn.setObjectName("profileBtn")
        self.verticalLayout_4.addWidget(self.profileBtn)
        self.sidebar.addWidget(self.accountGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 345, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.sidebar.addItem(spacerItem)
        self.gridLayout.addWidget(self.sidebar_2, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(698, 530))
        self.stackedWidget.setStyleSheet("background-color: rgb(231, 234, 239);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.ordersPage = QtWidgets.QWidget()
        self.ordersPage.setObjectName("ordersPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ordersPage)
        self.gridLayout_3.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.orderhistoryLbl = QtWidgets.QLabel(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderhistoryLbl.sizePolicy().hasHeightForWidth())
        self.orderhistoryLbl.setSizePolicy(sizePolicy)
        self.orderhistoryLbl.setObjectName("orderhistoryLbl")
        self.gridLayout_3.addWidget(self.orderhistoryLbl, 0, 0, 1, 1)
        self.showLbl = QtWidgets.QLabel(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showLbl.sizePolicy().hasHeightForWidth())
        self.showLbl.setSizePolicy(sizePolicy)
        self.showLbl.setObjectName("showLbl")
        self.gridLayout_3.addWidget(self.showLbl, 1, 0, 1, 1)
        self.orderTable = QtWidgets.QTableView(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderTable.sizePolicy().hasHeightForWidth())
        self.orderTable.setSizePolicy(sizePolicy)
        self.orderTable.setMinimumSize(QtCore.QSize(0, 0))
        self.orderTable.setStyleSheet("alternate-background-color: rgb(241, 241, 241);\n"
"background-color: rgb(255, 255, 255);")
        self.orderTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.orderTable.setSortingEnabled(True)
        self.orderTable.setObjectName("orderTable")
        self.orderTable.horizontalHeader().setCascadingSectionResizes(True)
        self.orderTable.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.orderTable, 4, 0, 1, 3)
        self.showCombo = QtWidgets.QComboBox(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showCombo.sizePolicy().hasHeightForWidth())
        self.showCombo.setSizePolicy(sizePolicy)
        self.showCombo.setMinimumSize(QtCore.QSize(81, 20))
        self.showCombo.setMaximumSize(QtCore.QSize(158, 20))
        self.showCombo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.showCombo.setObjectName("showCombo")
        self.showCombo.addItem("")
        self.showCombo.addItem("")
        self.showCombo.addItem("")
        self.showCombo.addItem("")
        self.gridLayout_3.addWidget(self.showCombo, 2, 0, 1, 1)
        self.searchLbl = QtWidgets.QLabel(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLbl.sizePolicy().hasHeightForWidth())
        self.searchLbl.setSizePolicy(sizePolicy)
        self.searchLbl.setObjectName("searchLbl")
        self.gridLayout_3.addWidget(self.searchLbl, 1, 2, 1, 1)
        self.orderSearchLE = QtWidgets.QLineEdit(self.ordersPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderSearchLE.sizePolicy().hasHeightForWidth())
        self.orderSearchLE.setSizePolicy(sizePolicy)
        self.orderSearchLE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.orderSearchLE.setObjectName("orderSearchLE")
        self.gridLayout_3.addWidget(self.orderSearchLE, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.ordersPage)
        self.inboxPage = QtWidgets.QWidget()
        self.inboxPage.setObjectName("inboxPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.inboxPage)
        self.gridLayout_2.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.inboxPage)
        self.frame.setMaximumSize(QtCore.QSize(95, 137))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inboxBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inboxBtn.sizePolicy().hasHeightForWidth())
        self.inboxBtn.setSizePolicy(sizePolicy)
        self.inboxBtn.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.inboxBtn.setObjectName("inboxBtn")
        self.verticalLayout.addWidget(self.inboxBtn)
        self.unreadBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unreadBtn.sizePolicy().hasHeightForWidth())
        self.unreadBtn.setSizePolicy(sizePolicy)
        self.unreadBtn.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.unreadBtn.setObjectName("unreadBtn")
        self.verticalLayout.addWidget(self.unreadBtn)
        self.sentBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentBtn.sizePolicy().hasHeightForWidth())
        self.sentBtn.setSizePolicy(sizePolicy)
        self.sentBtn.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.sentBtn.setObjectName("sentBtn")
        self.verticalLayout.addWidget(self.sentBtn)
        self.trashBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trashBtn.sizePolicy().hasHeightForWidth())
        self.trashBtn.setSizePolicy(sizePolicy)
        self.trashBtn.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.trashBtn.setObjectName("trashBtn")
        self.verticalLayout.addWidget(self.trashBtn)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.inboxLbl = QtWidgets.QLabel(self.inboxPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inboxLbl.sizePolicy().hasHeightForWidth())
        self.inboxLbl.setSizePolicy(sizePolicy)
        self.inboxLbl.setTextFormat(QtCore.Qt.AutoText)
        self.inboxLbl.setObjectName("inboxLbl")
        self.gridLayout_2.addWidget(self.inboxLbl, 0, 0, 1, 1)
        self.inboxStackedWidget = QtWidgets.QStackedWidget(self.inboxPage)
        self.inboxStackedWidget.setObjectName("inboxStackedWidget")
        self.inboxTablePage = QtWidgets.QWidget()
        self.inboxTablePage.setObjectName("inboxTablePage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.inboxTablePage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.inboxTable = QtWidgets.QTableView(self.inboxTablePage)
        self.inboxTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inboxTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inboxTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.inboxTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.inboxTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.inboxTable.setShowGrid(False)
        self.inboxTable.setObjectName("inboxTable")
        self.inboxTable.horizontalHeader().setVisible(False)
        self.inboxTable.horizontalHeader().setHighlightSections(False)
        self.inboxTable.verticalHeader().setVisible(False)
        self.inboxTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_5.addWidget(self.inboxTable)
        self.inboxStackedWidget.addWidget(self.inboxTablePage)
        self.unreadTablePage = QtWidgets.QWidget()
        self.unreadTablePage.setObjectName("unreadTablePage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.unreadTablePage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.unreadTable = QtWidgets.QTableView(self.unreadTablePage)
        self.unreadTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.unreadTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.unreadTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.unreadTable.setObjectName("unreadTable")
        self.unreadTable.horizontalHeader().setVisible(False)
        self.unreadTable.horizontalHeader().setHighlightSections(False)
        self.unreadTable.verticalHeader().setVisible(False)
        self.unreadTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_6.addWidget(self.unreadTable)
        self.inboxStackedWidget.addWidget(self.unreadTablePage)
        self.sentTablePage = QtWidgets.QWidget()
        self.sentTablePage.setObjectName("sentTablePage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sentTablePage)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sentTable = QtWidgets.QTableView(self.sentTablePage)
        self.sentTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sentTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.sentTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sentTable.setObjectName("sentTable")
        self.sentTable.horizontalHeader().setVisible(False)
        self.sentTable.horizontalHeader().setHighlightSections(False)
        self.sentTable.verticalHeader().setVisible(False)
        self.sentTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_7.addWidget(self.sentTable)
        self.inboxStackedWidget.addWidget(self.sentTablePage)
        self.trashTablePage = QtWidgets.QWidget()
        self.trashTablePage.setObjectName("trashTablePage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.trashTablePage)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.trashTable = QtWidgets.QTableView(self.trashTablePage)
        self.trashTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.trashTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.trashTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.trashTable.setObjectName("trashTable")
        self.trashTable.horizontalHeader().setVisible(False)
        self.trashTable.horizontalHeader().setHighlightSections(False)
        self.trashTable.verticalHeader().setVisible(False)
        self.trashTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_8.addWidget(self.trashTable)
        self.inboxStackedWidget.addWidget(self.trashTablePage)
        self.gridLayout_2.addWidget(self.inboxStackedWidget, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.inboxPage)
        self.catalogPage = QtWidgets.QWidget()
        self.catalogPage.setObjectName("catalogPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.catalogPage)
        self.gridLayout_4.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.categoryCombo = QtWidgets.QComboBox(self.catalogPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryCombo.sizePolicy().hasHeightForWidth())
        self.categoryCombo.setSizePolicy(sizePolicy)
        self.categoryCombo.setMinimumSize(QtCore.QSize(81, 20))
        self.categoryCombo.setMaximumSize(QtCore.QSize(158, 20))
        self.categoryCombo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.categoryCombo.setObjectName("categoryCombo")
        self.gridLayout_4.addWidget(self.categoryCombo, 2, 0, 1, 1)
        self.catalogTable = QtWidgets.QTableView(self.catalogPage)
        self.catalogTable.setStyleSheet("alternate-background-color: rgb(241, 241, 241);\n"
"background-color: rgb(255, 255, 255);")
        self.catalogTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.catalogTable.setSortingEnabled(True)
        self.catalogTable.setObjectName("catalogTable")
        self.catalogTable.horizontalHeader().setCascadingSectionResizes(True)
        self.catalogTable.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.catalogTable, 3, 0, 1, 3)
        self.catLbl = QtWidgets.QLabel(self.catalogPage)
        self.catLbl.setObjectName("catLbl")
        self.gridLayout_4.addWidget(self.catLbl, 1, 0, 1, 1)
        self.addProductBtn = QtWidgets.QPushButton(self.catalogPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addProductBtn.sizePolicy().hasHeightForWidth())
        self.addProductBtn.setSizePolicy(sizePolicy)
        self.addProductBtn.setMinimumSize(QtCore.QSize(81, 20))
        self.addProductBtn.setMaximumSize(QtCore.QSize(111, 20))
        self.addProductBtn.setStyleSheet("border-color: rgb(62, 112, 201);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(62, 112, 201);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"")
        self.addProductBtn.setObjectName("addProductBtn")
        self.gridLayout_4.addWidget(self.addProductBtn, 2, 2, 1, 1)
        self.productCatalogLbl = QtWidgets.QLabel(self.catalogPage)
        self.productCatalogLbl.setObjectName("productCatalogLbl")
        self.gridLayout_4.addWidget(self.productCatalogLbl, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.catalogPage)
        self.pendingPage = QtWidgets.QWidget()
        self.pendingPage.setObjectName("pendingPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pendingPage)
        self.gridLayout_5.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pendCatLbl = QtWidgets.QLabel(self.pendingPage)
        self.pendCatLbl.setObjectName("pendCatLbl")
        self.gridLayout_5.addWidget(self.pendCatLbl, 1, 0, 1, 1)
        self.pendCatCombo = QtWidgets.QComboBox(self.pendingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pendCatCombo.sizePolicy().hasHeightForWidth())
        self.pendCatCombo.setSizePolicy(sizePolicy)
        self.pendCatCombo.setMinimumSize(QtCore.QSize(81, 20))
        self.pendCatCombo.setMaximumSize(QtCore.QSize(158, 20))
        self.pendCatCombo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pendCatCombo.setObjectName("pendCatCombo")
        self.gridLayout_5.addWidget(self.pendCatCombo, 2, 0, 1, 1)
        self.pendTable = QtWidgets.QTableView(self.pendingPage)
        self.pendTable.setStyleSheet("alternate-background-color: rgb(241, 241, 241);\n"
"background-color: rgb(255, 255, 255);")
        self.pendTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.pendTable.setSortingEnabled(True)
        self.pendTable.setObjectName("pendTable")
        self.pendTable.horizontalHeader().setCascadingSectionResizes(True)
        self.pendTable.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.pendTable, 3, 0, 1, 3)
        self.addPendProdBtn = QtWidgets.QPushButton(self.pendingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPendProdBtn.sizePolicy().hasHeightForWidth())
        self.addPendProdBtn.setSizePolicy(sizePolicy)
        self.addPendProdBtn.setMinimumSize(QtCore.QSize(81, 20))
        self.addPendProdBtn.setMaximumSize(QtCore.QSize(111, 20))
        self.addPendProdBtn.setStyleSheet("border-color: rgb(62, 112, 201);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(62, 112, 201);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"")
        self.addPendProdBtn.setObjectName("addPendProdBtn")
        self.gridLayout_5.addWidget(self.addPendProdBtn, 2, 2, 1, 1)
        self.pendUploadsLbl = QtWidgets.QLabel(self.pendingPage)
        self.pendUploadsLbl.setObjectName("pendUploadsLbl")
        self.gridLayout_5.addWidget(self.pendUploadsLbl, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pendingPage)
        self.profilePage = QtWidgets.QWidget()
        self.profilePage.setObjectName("profilePage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.profilePage)
        self.gridLayout_6.setContentsMargins(15, 15, 15, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 11, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.profilePage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 10, 0, 1, 1)
        self.paypalEmailLE = QtWidgets.QLineEdit(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paypalEmailLE.sizePolicy().hasHeightForWidth())
        self.paypalEmailLE.setSizePolicy(sizePolicy)
        self.paypalEmailLE.setMinimumSize(QtCore.QSize(300, 0))
        self.paypalEmailLE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.paypalEmailLE.setObjectName("paypalEmailLE")
        self.gridLayout_6.addWidget(self.paypalEmailLE, 7, 0, 1, 5)
        self.label = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/imgs/default-user-icon.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 2, 0, 1, 1)
        self.profileDescTE = QtWidgets.QTextEdit(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileDescTE.sizePolicy().hasHeightForWidth())
        self.profileDescTE.setSizePolicy(sizePolicy)
        self.profileDescTE.setMinimumSize(QtCore.QSize(0, 0))
        self.profileDescTE.setMaximumSize(QtCore.QSize(999999, 200))
        self.profileDescTE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.profileDescTE.setObjectName("profileDescTE")
        self.gridLayout_6.addWidget(self.profileDescTE, 5, 0, 1, 1)
        self.emailconfidLbl = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailconfidLbl.sizePolicy().hasHeightForWidth())
        self.emailconfidLbl.setSizePolicy(sizePolicy)
        self.emailconfidLbl.setObjectName("emailconfidLbl")
        self.gridLayout_6.addWidget(self.emailconfidLbl, 8, 0, 1, 1)
        self.paypalEmailLbl = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paypalEmailLbl.sizePolicy().hasHeightForWidth())
        self.paypalEmailLbl.setSizePolicy(sizePolicy)
        self.paypalEmailLbl.setObjectName("paypalEmailLbl")
        self.gridLayout_6.addWidget(self.paypalEmailLbl, 6, 0, 1, 1)
        self.profileDescLbl = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileDescLbl.sizePolicy().hasHeightForWidth())
        self.profileDescLbl.setSizePolicy(sizePolicy)
        self.profileDescLbl.setObjectName("profileDescLbl")
        self.gridLayout_6.addWidget(self.profileDescLbl, 4, 0, 1, 1)
        self.profileLbl = QtWidgets.QLabel(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileLbl.sizePolicy().hasHeightForWidth())
        self.profileLbl.setSizePolicy(sizePolicy)
        self.profileLbl.setObjectName("profileLbl")
        self.gridLayout_6.addWidget(self.profileLbl, 0, 0, 1, 1)
        self.profileSaveBtn = QtWidgets.QPushButton(self.profilePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileSaveBtn.sizePolicy().hasHeightForWidth())
        self.profileSaveBtn.setSizePolicy(sizePolicy)
        self.profileSaveBtn.setMinimumSize(QtCore.QSize(80, 20))
        self.profileSaveBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileSaveBtn.setStyleSheet("background-color: rgb(63, 112, 199);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"alternate-background-color: rgb(50, 90, 159);")
        self.profileSaveBtn.setFlat(False)
        self.profileSaveBtn.setObjectName("profileSaveBtn")
        self.gridLayout_6.addWidget(self.profileSaveBtn, 9, 0, 1, 1)
        self.stackedWidget.addWidget(self.profilePage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        HSMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HSMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuSynchronize = QtWidgets.QMenu(self.menuFile)
        self.menuSynchronize.setObjectName("menuSynchronize")
        self.menuLoad = QtWidgets.QMenu(self.menuFile)
        self.menuLoad.setObjectName("menuLoad")
        self.menuExport_CSV = QtWidgets.QMenu(self.menuFile)
        self.menuExport_CSV.setObjectName("menuExport_CSV")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        HSMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HSMainWindow)
        self.statusbar.setObjectName("statusbar")
        HSMainWindow.setStatusBar(self.statusbar)
        self.actionNewItem = QtWidgets.QAction(HSMainWindow)
        self.actionNewItem.setObjectName("actionNewItem")
        self.actionTemplate = QtWidgets.QAction(HSMainWindow)
        self.actionTemplate.setObjectName("actionTemplate")
        self.actionClose = QtWidgets.QAction(HSMainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAll_Items = QtWidgets.QAction(HSMainWindow)
        self.actionAll_Items.setObjectName("actionAll_Items")
        self.actionCheck_for_New_Items = QtWidgets.QAction(HSMainWindow)
        self.actionCheck_for_New_Items.setObjectName("actionCheck_for_New_Items")
        self.actionUpload_Waiting_Items = QtWidgets.QAction(HSMainWindow)
        self.actionUpload_Waiting_Items.setObjectName("actionUpload_Waiting_Items")
        self.actionN_A = QtWidgets.QAction(HSMainWindow)
        self.actionN_A.setObjectName("actionN_A")
        self.actionInventory_CSV = QtWidgets.QAction(HSMainWindow)
        self.actionInventory_CSV.setObjectName("actionInventory_CSV")
        self.actionActive_Catalog = QtWidgets.QAction(HSMainWindow)
        self.actionActive_Catalog.setObjectName("actionActive_Catalog")
        self.actionInactive_Items = QtWidgets.QAction(HSMainWindow)
        self.actionInactive_Items.setObjectName("actionInactive_Items")
        self.actionGlobal_Catalog = QtWidgets.QAction(HSMainWindow)
        self.actionGlobal_Catalog.setObjectName("actionGlobal_Catalog")
        self.menuNew.addAction(self.actionNewItem)
        self.menuNew.addAction(self.actionTemplate)
        self.menuSynchronize.addAction(self.actionAll_Items)
        self.menuSynchronize.addAction(self.actionCheck_for_New_Items)
        self.menuSynchronize.addAction(self.actionUpload_Waiting_Items)
        self.menuLoad.addAction(self.actionInventory_CSV)
        self.menuExport_CSV.addAction(self.actionActive_Catalog)
        self.menuExport_CSV.addAction(self.actionInactive_Items)
        self.menuExport_CSV.addAction(self.actionGlobal_Catalog)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addAction(self.menuExport_CSV.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSynchronize.menuAction())
        self.menuHelp.addAction(self.actionN_A)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HSMainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.inboxStackedWidget.setCurrentIndex(0)
        self.ordersBtn.clicked.connect(HSMainWindow.initOrdersView)
        self.messagesBtn.clicked.connect(HSMainWindow.initInboxView)
        self.productsBtn.clicked.connect(HSMainWindow.initProductsView)
        self.pendBtn.clicked.connect(HSMainWindow.initPendingView)
        self.profileBtn.clicked.connect(HSMainWindow.initProfileView)
        self.pushButton_2.clicked.connect(HSMainWindow.changeProfileIcon)
        self.showCombo.currentIndexChanged['QString'].connect(HSMainWindow.changeOrderTableLength)
        self.orderSearchLE.textEdited['QString'].connect(HSMainWindow.searchOrderTable)
        self.addPendProdBtn.clicked.connect(HSMainWindow.addProduct)
        self.pendCatCombo.currentIndexChanged['QString'].connect(HSMainWindow.filterPendingProductsTable)
        self.pushButton.clicked.connect(HSMainWindow.addProduct)
        self.categoryCombo.currentIndexChanged['QString'].connect(HSMainWindow.filterProductsTable)
        self.addProductBtn.clicked.connect(HSMainWindow.addProduct)
        self.inboxBtn.clicked.connect(HSMainWindow.switchInboxTable)
        self.unreadBtn.clicked.connect(HSMainWindow.switchUnreadTable)
        self.sentBtn.clicked.connect(HSMainWindow.switchSentTable)
        self.trashBtn.clicked.connect(HSMainWindow.switchTrashTable)
        self.profileSaveBtn.clicked.connect(HSMainWindow.saveProfileChanges)
        QtCore.QMetaObject.connectSlotsByName(HSMainWindow)
        HSMainWindow.setTabOrder(self.pushButton, self.productsBtn)
        HSMainWindow.setTabOrder(self.productsBtn, self.pendBtn)
        HSMainWindow.setTabOrder(self.pendBtn, self.ordersBtn)
        HSMainWindow.setTabOrder(self.ordersBtn, self.messagesBtn)
        HSMainWindow.setTabOrder(self.messagesBtn, self.profileBtn)
        HSMainWindow.setTabOrder(self.profileBtn, self.inboxBtn)
        HSMainWindow.setTabOrder(self.inboxBtn, self.unreadBtn)
        HSMainWindow.setTabOrder(self.unreadBtn, self.sentBtn)
        HSMainWindow.setTabOrder(self.sentBtn, self.trashBtn)

    def retranslateUi(self, HSMainWindow):
        _translate = QtCore.QCoreApplication.translate
        HSMainWindow.setWindowTitle(_translate("HSMainWindow", "HangarSwap Seller App"))
        self.catalogGroupBox.setTitle(_translate("HSMainWindow", "Catalog"))
        self.pushButton.setText(_translate("HSMainWindow", "Add Product"))
        self.productsBtn.setText(_translate("HSMainWindow", "Products"))
        self.pendBtn.setText(_translate("HSMainWindow", "Waiting to Upload"))
        self.salesGroupBox.setTitle(_translate("HSMainWindow", "Sales"))
        self.ordersBtn.setText(_translate("HSMainWindow", "Order History"))
        self.accountGroupBox.setTitle(_translate("HSMainWindow", "My Account"))
        self.messagesBtn.setText(_translate("HSMainWindow", "Messages"))
        self.profileBtn.setText(_translate("HSMainWindow", "Profile"))
        self.orderhistoryLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Order History</span></p></body></html>"))
        self.showLbl.setText(_translate("HSMainWindow", "Show:"))
        self.showCombo.setItemText(0, _translate("HSMainWindow", "10"))
        self.showCombo.setItemText(1, _translate("HSMainWindow", "25"))
        self.showCombo.setItemText(2, _translate("HSMainWindow", "50"))
        self.showCombo.setItemText(3, _translate("HSMainWindow", "100"))
        self.searchLbl.setText(_translate("HSMainWindow", "Search:"))
        self.inboxBtn.setText(_translate("HSMainWindow", "Inbox"))
        self.unreadBtn.setText(_translate("HSMainWindow", "Unread"))
        self.sentBtn.setText(_translate("HSMainWindow", "Sent"))
        self.trashBtn.setText(_translate("HSMainWindow", "Trash"))
        self.inboxLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Inbox</span></p></body></html>"))
        self.catLbl.setText(_translate("HSMainWindow", "Category Filter:"))
        self.addProductBtn.setText(_translate("HSMainWindow", "Add Product +"))
        self.productCatalogLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Product Catalog</span></p></body></html>"))
        self.pendCatLbl.setText(_translate("HSMainWindow", "Category Filter:"))
        self.addPendProdBtn.setText(_translate("HSMainWindow", "Add Product +"))
        self.pendUploadsLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Pending Uploads</span></p></body></html>"))
        self.pushButton_2.setText(_translate("HSMainWindow", "Change Icon"))
        self.emailconfidLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#515558;\">We\'ll never share your email with anyone else.</span></p></body></html>"))
        self.paypalEmailLbl.setText(_translate("HSMainWindow", "Paypal Email Address"))
        self.profileDescLbl.setText(_translate("HSMainWindow", "Seller Profile Description"))
        self.profileLbl.setText(_translate("HSMainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">My Seller Profile</span></p></body></html>"))
        self.profileSaveBtn.setText(_translate("HSMainWindow", "Save Changes"))
        self.menuFile.setTitle(_translate("HSMainWindow", "File"))
        self.menuNew.setTitle(_translate("HSMainWindow", "New"))
        self.menuSynchronize.setTitle(_translate("HSMainWindow", "Synchronize"))
        self.menuLoad.setTitle(_translate("HSMainWindow", "Load"))
        self.menuExport_CSV.setTitle(_translate("HSMainWindow", "Export CSV"))
        self.menuHelp.setTitle(_translate("HSMainWindow", "Help"))
        self.actionNewItem.setText(_translate("HSMainWindow", "Item"))
        self.actionTemplate.setText(_translate("HSMainWindow", "Template"))
        self.actionClose.setText(_translate("HSMainWindow", "Close"))
        self.actionAll_Items.setText(_translate("HSMainWindow", "All Items"))
        self.actionCheck_for_New_Items.setText(_translate("HSMainWindow", "Check for New Items"))
        self.actionUpload_Waiting_Items.setText(_translate("HSMainWindow", "Upload Waiting Items"))
        self.actionN_A.setText(_translate("HSMainWindow", "N/A"))
        self.actionInventory_CSV.setText(_translate("HSMainWindow", "Inventory CSV"))
        self.actionActive_Catalog.setText(_translate("HSMainWindow", "Active"))
        self.actionInactive_Items.setText(_translate("HSMainWindow", "Inactive"))
        self.actionGlobal_Catalog.setText(_translate("HSMainWindow", "Global Catalog"))

import RESOURCES
