# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_redesign.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HSMainWindow(object):
    def setupUi(self, HSMainWindow):
        HSMainWindow.setObjectName("HSMainWindow")
        HSMainWindow.resize(849, 632)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HSMainWindow.sizePolicy().hasHeightForWidth())
        HSMainWindow.setSizePolicy(sizePolicy)
        HSMainWindow.setMinimumSize(QtCore.QSize(849, 632))
        HSMainWindow.setMouseTracking(True)
        HSMainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        HSMainWindow.setStyleSheet("QMenuBar {\n"
"    background-color: rgb(54, 56, 67);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        HSMainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        HSMainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(HSMainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sidebar_2 = QtWidgets.QFrame(self.centralwidget)
        self.sidebar_2.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"font: 8pt \"Open Sans\";\n"
"QPushButton {cursor:\"Pointing Hand\";}")
        self.sidebar_2.setObjectName("sidebar_2")
        self.sidebar = QtWidgets.QVBoxLayout(self.sidebar_2)
        self.sidebar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.sidebar.setSpacing(0)
        self.sidebar.setObjectName("sidebar")
        self.catalogGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catalogGroupBox.sizePolicy().hasHeightForWidth())
        self.catalogGroupBox.setSizePolicy(sizePolicy)
        self.catalogGroupBox.setFlat(True)
        self.catalogGroupBox.setObjectName("catalogGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.catalogGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.productsBtn = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productsBtn.sizePolicy().hasHeightForWidth())
        self.productsBtn.setSizePolicy(sizePolicy)
        self.productsBtn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.productsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.productsBtn.setStyleSheet("")
        self.productsBtn.setCheckable(False)
        self.productsBtn.setAutoExclusive(True)
        self.productsBtn.setFlat(False)
        self.productsBtn.setObjectName("productsBtn")
        self.verticalLayout_2.addWidget(self.productsBtn)
        self.pendBtn = QtWidgets.QPushButton(self.catalogGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pendBtn.sizePolicy().hasHeightForWidth())
        self.pendBtn.setSizePolicy(sizePolicy)
        self.pendBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pendBtn.setObjectName("pendBtn")
        self.main_view_group = QtWidgets.QButtonGroup(HSMainWindow)
        self.main_view_group.setObjectName("main_view_group")
        self.main_view_group.addButton(self.pendBtn)
        self.verticalLayout_2.addWidget(self.pendBtn)
        self.sidebar.addWidget(self.catalogGroupBox)
        self.salesGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salesGroupBox.sizePolicy().hasHeightForWidth())
        self.salesGroupBox.setSizePolicy(sizePolicy)
        self.salesGroupBox.setFlat(True)
        self.salesGroupBox.setObjectName("salesGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.salesGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ordersBtn = QtWidgets.QPushButton(self.salesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ordersBtn.sizePolicy().hasHeightForWidth())
        self.ordersBtn.setSizePolicy(sizePolicy)
        self.ordersBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ordersBtn.setObjectName("ordersBtn")
        self.verticalLayout_3.addWidget(self.ordersBtn)
        self.sidebar.addWidget(self.salesGroupBox)
        self.accountGroupBox = QtWidgets.QGroupBox(self.sidebar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountGroupBox.sizePolicy().hasHeightForWidth())
        self.accountGroupBox.setSizePolicy(sizePolicy)
        self.accountGroupBox.setFlat(True)
        self.accountGroupBox.setObjectName("accountGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.accountGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.messagesBtn = QtWidgets.QPushButton(self.accountGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messagesBtn.sizePolicy().hasHeightForWidth())
        self.messagesBtn.setSizePolicy(sizePolicy)
        self.messagesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.messagesBtn.setObjectName("messagesBtn")
        self.verticalLayout_4.addWidget(self.messagesBtn, 0, QtCore.Qt.AlignLeft)
        self.profileBtn = QtWidgets.QPushButton(self.accountGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileBtn.sizePolicy().hasHeightForWidth())
        self.profileBtn.setSizePolicy(sizePolicy)
        self.profileBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileBtn.setObjectName("profileBtn")
        self.verticalLayout_4.addWidget(self.profileBtn)
        self.sidebar.addWidget(self.accountGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 345, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.sidebar.addItem(spacerItem)
        self.gridLayout.addWidget(self.sidebar_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(698, 530))
        self.widget.setStyleSheet("background-color: rgb(231, 234, 239);")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        HSMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HSMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuSynchronize = QtWidgets.QMenu(self.menuFile)
        self.menuSynchronize.setObjectName("menuSynchronize")
        self.menuLoad = QtWidgets.QMenu(self.menuFile)
        self.menuLoad.setObjectName("menuLoad")
        self.menuExport_CSV = QtWidgets.QMenu(self.menuFile)
        self.menuExport_CSV.setObjectName("menuExport_CSV")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        HSMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HSMainWindow)
        self.statusbar.setObjectName("statusbar")
        HSMainWindow.setStatusBar(self.statusbar)
        self.actionNewItem = QtWidgets.QAction(HSMainWindow)
        self.actionNewItem.setObjectName("actionNewItem")
        self.actionTemplate = QtWidgets.QAction(HSMainWindow)
        self.actionTemplate.setObjectName("actionTemplate")
        self.actionClose = QtWidgets.QAction(HSMainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAll_Items = QtWidgets.QAction(HSMainWindow)
        self.actionAll_Items.setObjectName("actionAll_Items")
        self.actionCheck_for_New_Items = QtWidgets.QAction(HSMainWindow)
        self.actionCheck_for_New_Items.setObjectName("actionCheck_for_New_Items")
        self.actionUpload_Waiting_Items = QtWidgets.QAction(HSMainWindow)
        self.actionUpload_Waiting_Items.setObjectName("actionUpload_Waiting_Items")
        self.actionN_A = QtWidgets.QAction(HSMainWindow)
        self.actionN_A.setObjectName("actionN_A")
        self.actionInventory_CSV = QtWidgets.QAction(HSMainWindow)
        self.actionInventory_CSV.setObjectName("actionInventory_CSV")
        self.actionActive_Catalog = QtWidgets.QAction(HSMainWindow)
        self.actionActive_Catalog.setObjectName("actionActive_Catalog")
        self.actionInactive_Items = QtWidgets.QAction(HSMainWindow)
        self.actionInactive_Items.setObjectName("actionInactive_Items")
        self.actionGlobal_Catalog = QtWidgets.QAction(HSMainWindow)
        self.actionGlobal_Catalog.setObjectName("actionGlobal_Catalog")
        self.menuNew.addAction(self.actionNewItem)
        self.menuNew.addAction(self.actionTemplate)
        self.menuSynchronize.addAction(self.actionAll_Items)
        self.menuSynchronize.addAction(self.actionCheck_for_New_Items)
        self.menuSynchronize.addAction(self.actionUpload_Waiting_Items)
        self.menuLoad.addAction(self.actionInventory_CSV)
        self.menuExport_CSV.addAction(self.actionActive_Catalog)
        self.menuExport_CSV.addAction(self.actionInactive_Items)
        self.menuExport_CSV.addAction(self.actionGlobal_Catalog)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addAction(self.menuExport_CSV.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSynchronize.menuAction())
        self.menuHelp.addAction(self.actionN_A)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HSMainWindow)
        QtCore.QMetaObject.connectSlotsByName(HSMainWindow)
        HSMainWindow.setTabOrder(self.productsBtn, self.pendBtn)
        HSMainWindow.setTabOrder(self.pendBtn, self.ordersBtn)
        HSMainWindow.setTabOrder(self.ordersBtn, self.messagesBtn)
        HSMainWindow.setTabOrder(self.messagesBtn, self.profileBtn)

    def retranslateUi(self, HSMainWindow):
        _translate = QtCore.QCoreApplication.translate
        HSMainWindow.setWindowTitle(_translate("HSMainWindow", "HangarSwap Seller App"))
        self.catalogGroupBox.setTitle(_translate("HSMainWindow", "Catalog"))
        self.pushButton.setText(_translate("HSMainWindow", "Add Product"))
        self.productsBtn.setText(_translate("HSMainWindow", "Products"))
        self.pendBtn.setText(_translate("HSMainWindow", "Waiting to Upload"))
        self.salesGroupBox.setTitle(_translate("HSMainWindow", "Sales"))
        self.ordersBtn.setText(_translate("HSMainWindow", "Order History"))
        self.accountGroupBox.setTitle(_translate("HSMainWindow", "My Account"))
        self.messagesBtn.setText(_translate("HSMainWindow", "Messages"))
        self.profileBtn.setText(_translate("HSMainWindow", "Profile"))
        self.menuFile.setTitle(_translate("HSMainWindow", "File"))
        self.menuNew.setTitle(_translate("HSMainWindow", "New"))
        self.menuSynchronize.setTitle(_translate("HSMainWindow", "Synchronize"))
        self.menuLoad.setTitle(_translate("HSMainWindow", "Load"))
        self.menuExport_CSV.setTitle(_translate("HSMainWindow", "Export CSV"))
        self.menuHelp.setTitle(_translate("HSMainWindow", "Help"))
        self.actionNewItem.setText(_translate("HSMainWindow", "Item"))
        self.actionTemplate.setText(_translate("HSMainWindow", "Template"))
        self.actionClose.setText(_translate("HSMainWindow", "Close"))
        self.actionAll_Items.setText(_translate("HSMainWindow", "All Items"))
        self.actionCheck_for_New_Items.setText(_translate("HSMainWindow", "Check for New Items"))
        self.actionUpload_Waiting_Items.setText(_translate("HSMainWindow", "Upload Waiting Items"))
        self.actionN_A.setText(_translate("HSMainWindow", "N/A"))
        self.actionInventory_CSV.setText(_translate("HSMainWindow", "Inventory CSV"))
        self.actionActive_Catalog.setText(_translate("HSMainWindow", "Active"))
        self.actionInactive_Items.setText(_translate("HSMainWindow", "Inactive"))
        self.actionGlobal_Catalog.setText(_translate("HSMainWindow", "Global Catalog"))

